// Generate the bundled .cube 3D LUTs (assets/luts/*.cube) procedurally — no
// licensed LUT packs. Each look is a small per-RGB formula sampled on a 33^3
// grid; the engine applies them via colorGrade.lut -> lut3d (already wired in
// buildColorFilter). Keep formulas gentle: LUTs stack UNDER the rest of the
// grade chain (eq -> curves -> lut -> temperature -> glow...), so themes can
// still add contrast/glow on top.
//
// Usage: node scripts/generateLuts.mjs [--only teal_orange_01]
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const SIZE = 33;

const clamp01 = (v) => Math.min(1, Math.max(0, v));
const lerp = (a, b, t) => a + (b - a) * t;
const luma = (r, g, b) => 0.2126 * r + 0.7152 * g + 0.0722 * b;
const smooth = (v) => v * v * (3 - 2 * v); // gentle S-curve when mixed in

/** Soft highlight shoulder: linear below the knee, compressed above. */
function rolloff(v, knee = 0.78, strength = 0.35) {
  return v <= knee ? v : knee + (v - knee) * (1 - strength);
}

const LUTS = {
  // 2026 editorial: teal shadows, orange highlights, S-curve, slight desat.
  teal_orange_01: (r, g, b) => {
    const Y = luma(r, g, b);
    const sh = (1 - Y) ** 2;
    const hi = Y ** 2;
    r = r + 0.055 * hi - 0.05 * sh;
    g = g + 0.008 * hi + 0.014 * sh;
    b = b - 0.055 * hi + 0.08 * sh;
    const c = 0.3;
    r = lerp(r, smooth(clamp01(r)), c);
    g = lerp(g, smooth(clamp01(g)), c);
    b = lerp(b, smooth(clamp01(b)), c);
    const Y2 = luma(r, g, b);
    const d = 0.07;
    return [lerp(r, Y2, d), lerp(g, Y2, d), lerp(b, Y2, d)];
  },

  // Moody earth: desaturated, warm mids, lifted faded blacks, soft contrast.
  moody_earth_01: (r, g, b) => {
    const Y = luma(r, g, b);
    const d = 0.2;
    r = lerp(r, Y, d);
    g = lerp(g, Y, d);
    b = lerp(b, Y, d);
    const mid = Y * (1 - Y) * 4; // peaks at Y=0.5
    r += 0.028 * mid;
    g += 0.006 * mid;
    b -= 0.03 * mid;
    r = 0.028 + r * 0.955;
    g = 0.028 + g * 0.955;
    b = 0.034 + b * 0.948;
    const c = 0.2;
    r = lerp(r, smooth(clamp01(r)), c);
    g = lerp(g, smooth(clamp01(g)), c);
    b = lerp(b, smooth(clamp01(b)), c);
    return [r, g, b];
  },

  // Super-8 Kodak-ish home movie: warm cast, faded blacks with a green tinge
  // in the shadows, compressed highlights, slightly rich chroma.
  super8_kodak_01: (r, g, b) => {
    r = r * 1.07 + 0.012;
    g = g * 1.005;
    b = b * 0.9 + 0.008;
    const Y = clamp01(luma(r, g, b));
    g += 0.022 * (1 - Y) ** 2; // aged-print green shadows
    r = 0.045 + r * 0.935;
    g = 0.045 + g * 0.935;
    b = 0.055 + b * 0.925;
    r = rolloff(r);
    g = rolloff(g);
    b = rolloff(b);
    const Y2 = luma(r, g, b);
    const sat = 1.08; // push chroma slightly for that reversal-film pop
    return [
      Y2 + (r - Y2) * sat,
      Y2 + (g - Y2) * sat,
      Y2 + (b - Y2) * sat,
    ];
  },
};

const onlyIdx = process.argv.indexOf("--only");
const only = onlyIdx >= 0 ? process.argv[onlyIdx + 1] : null;

const outDir = path.resolve(root, "assets/luts");
fs.mkdirSync(outDir, { recursive: true });

for (const [name, fn] of Object.entries(LUTS)) {
  if (only && only !== name) continue;
  const lines = [
    `# Generated by scripts/generateLuts.mjs — ${name}`,
    `TITLE "${name}"`,
    `LUT_3D_SIZE ${SIZE}`,
  ];
  // .cube ordering: red varies fastest, then green, then blue.
  for (let bi = 0; bi < SIZE; bi++) {
    for (let gi = 0; gi < SIZE; gi++) {
      for (let ri = 0; ri < SIZE; ri++) {
        const [r, g, b] = fn(ri / (SIZE - 1), gi / (SIZE - 1), bi / (SIZE - 1));
        lines.push(
          `${clamp01(r).toFixed(6)} ${clamp01(g).toFixed(6)} ${clamp01(b).toFixed(6)}`
        );
      }
    }
  }
  const out = path.join(outDir, `${name}.cube`);
  fs.writeFileSync(out, lines.join("\n") + "\n");
  console.log(`wrote assets/luts/${name}.cube (${Math.round(fs.statSync(out).size / 1024)} KB)`);
}
