// Phase E / node 11 — the closed QA loop with a HARD revision cap.
//
// Layers, per PIPELINE-V1-VA-LITE.md §11:
//   1. rule-based, no AI   -> qaClip.mjs   (too_dark / too_bright / flat)   [needs the video]
//   2. measurable proxies  -> qaProxy.mjs  (pacing, hero)                    [no video needed]
//   3. the one subjective  -> qaProxy bookend (opening/ending)               [needs video + vision]
//
// Structure follows from what each layer costs:
//
//   PRE-FLIGHT (free)  proxy -> fix -> proxy ... until clean. Pacing and hero
//       need no rendered frames, so these repairs cost nothing and do NOT spend
//       the revision budget. Bounded by a fix-once rule (structural — see below)
//       and a generous PREFLIGHT_SAFETY_CAP passes, not by an aesthetic guess.
//   RENDER
//   REVISE (expensive) qaClip + proxy -> fix -> re-render. Each pass here spends
//       one revision. Hard cap --max-revisions (default 2). On exhaustion we
//       DELIVER the current cut and flag it for manual review — never loop.
//
// Every fix is deterministic (node 9's argument): the timeline is generated by
// code from already-guardrailed enums, so what QA finds is mechanical — a
// duration that fights the music, a hero slot holding a weak photo, a scene that
// rendered dark. Code repairs those directly. Re-prompting a model would be
// slower, non-reproducible, and is what makes aesthetic QA loop forever.
//
// Anti-oscillation: a (scene, check) pair is repaired at most once. Changing one
// slide's duration shifts every later slide's start time and therefore its own
// expected duration, so an unbounded "fix everything each pass" would chase its
// own tail. The fix-once rule plus the cap make termination structural.
//
// Usage: node scripts/qaLoop.mjs [--timeline timeline/quoc-nhi-full-v2.json]
//   [--content analysis/photo_content.json] [--max-revisions 2] [--skip-render]
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { appendFeedback } from "./lib/feedbackLedger.mjs";
import { actionFor } from "./lib/rules/policy.mjs";

const root = process.cwd();
const node = process.execPath;
const arg = (flag, def) => {
  const i = process.argv.indexOf(flag);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : def;
};

const TL = arg("--timeline", "timeline/quoc-nhi-full-v2.json");
// Reports belong to whoever owns the timeline. Derive that from the timeline's own
// location (`<job>/timeline/x.json` -> `<job>/analysis`) instead of a fixed root
// path, or a project run drops its QA report into the shared root — where the next
// job picks it up as its own. A root timeline still resolves to plain "analysis".
const siblingAnalysis = path.posix.join(path.dirname(path.dirname(TL.replace(/\\/g, "/"))), "analysis");
const analysisDir = arg("--analysis-dir", siblingAnalysis).replace(/\\/g, "/").replace(/\/$/, "");
const contentPath = arg("--content", `${analysisDir}/photo_content.json`);
const photosPath = arg("--photos", "");
const musicPath = arg("--music", "");
const jobDir = arg("--job-dir", "");
const MAX_REVISIONS = Number(arg("--max-revisions", "2"));
// Which repairs this tier is ALLOWED to apply comes from lib/rules/policy.mjs.
// Premium is the default because it matches the historical behavior of a direct
// invocation: every deterministic fix may run.
const TIER = arg("--tier", "premium");
// Fixing scene N's duration shifts every later scene's start time, which can surface a
// pacing mismatch on a scene that measured clean a pass ago — a cascade, not oscillation
// (the fix-once rule below still makes it terminate; a fixed small cap just cut it off
// before it finished). Found on city-to-ceremony-01/lively: a 54-scene timeline cascaded
// for 3 passes still finding new fixes, so a hard 3-pass cap left one genuinely fixable
// s05_ready_r4:pacing finding unrepaired and reported as a false "review". This step is
// free (no render, no AI), so the cap only needs to be generous, not tight.
const PREFLIGHT_SAFETY_CAP = 30;
const skipRender = process.argv.includes("--skip-render");
const skipInitialRender = process.argv.includes("--skip-initial-render");
const strict = process.argv.includes("--strict");

const tlAbs = path.resolve(root, TL);
if (!fs.existsSync(tlAbs)) { console.error(`[qaLoop] FAILED: timeline not found: ${TL}`); process.exit(1); }
const base = path.basename(TL).replace(/\.[^.]+$/, "");
const proxyOut = `${analysisDir}/qa/${base}.proxy.json`;
const clipOut = `${analysisDir}/qa/${base}.json`;

const readJson = (p) => JSON.parse(fs.readFileSync(path.resolve(root, p), "utf8"));
const writeTl = (tl) => fs.writeFileSync(tlAbs, JSON.stringify(tl, null, 2));

function sh(args, label) {
  const r = spawnSync(node, args, { cwd: root, encoding: "utf8", maxBuffer: 1 << 26 });
  if (r.status !== 0) {
    process.stderr.write((r.stdout || "") + (r.stderr || ""));
    throw new Error(`${label} failed (exit ${r.status})`);
  }
  return r;
}

const runProxy = () => {
  sh(["scripts/qaProxy.mjs", TL, "--content", contentPath, "--out", proxyOut, "--analysis-dir", analysisDir,
    ...(photosPath ? ["--photos", photosPath] : []), ...(musicPath ? ["--music", musicPath] : [])], "qaProxy");
  return readJson(proxyOut);
};
const runClip = () => {
  sh(["scripts/qaClip.mjs", TL, "--out", clipOut], "qaClip");
  return readJson(clipOut);
};
const render = () => {
  const args = ["--import", "tsx", "src/index.ts", "--timeline", TL];
  if (jobDir) args.push("--job-dir", jobDir);
  const r = spawnSync(node, args, { cwd: root, encoding: "utf8", maxBuffer: 1 << 26 });
  if (r.status !== 0) {
    console.error((r.stdout || "").split("\n").slice(-8).join("\n") + (r.stderr || ""));
    throw new Error(`render failed (exit ${r.status})`);
  }
};

// --- deterministic fixes ---------------------------------------------------
const repaired = new Set(); // "<sceneId>:<check>" — fix each pair at most once

/** Apply the fixes qaProxy proposed. Returns the list actually applied. */
function applyProxyFixes(report) {
  const tl = readJson(TL);
  const applied = [];
  for (const p of report.problems) {
    if (!p.fix) continue;                       // e.g. hero_not_in_content: needs re-analysis, not a swap
    if (actionFor(TIER, p.check) !== "repair") continue; // this tier reports the rule but may not touch the film for it
    const key = `${p.id}:${p.check}${Number.isInteger(p.fix.layer) ? `:${p.fix.layer}` : ""}`;
    if (repaired.has(key)) continue;            // anti-oscillation
    const slide = tl.slides.find((s) => s.id === p.id);
    if (!slide) continue;

    if (p.fix.kind === "set_duration") {
      const from = slide.duration;
      slide.duration = p.fix.to;
      applied.push(`${p.id}: duration ${from}s -> ${p.fix.to}s (${p.flags.join(",")})`);
    } else if (p.fix.kind === "swap_hero") {
      const l = slide.layers?.[p.fix.layer];
      if (!l || l.type !== "image") continue;
      const from = l.path;
      l.path = p.fix.to;
      l.focusX = p.fix.focusX;
      l.focusY = p.fix.focusY;
      applied.push(`${p.id}: hero ${from} -> ${p.fix.to} (${p.flags.join(",")})`);
    } else if (p.fix.kind === "set_focus") {
      const l = slide.layers?.[p.fix.layer];
      if (!l || l.type !== "image") continue;
      l.focusX = p.fix.focusX; l.focusY = p.fix.focusY;
      applied.push(`${p.id}: focus -> ${p.fix.focusX.toFixed(3)},${p.fix.focusY.toFixed(3)} (${p.flags.join(",")})`);
    } else if (p.fix.kind === "set_fit") {
      const l = slide.layers?.[p.fix.layer];
      if (!l || l.type !== "image") continue;
      l.fit = p.fix.to;
      l.focusX = 0.5; l.focusY = 0.5;
      applied.push(`${p.id}: fit -> ${p.fix.to} (${p.flags.join(",")})`);
    } else if (p.fix.kind === "fit_text") {
      // The shared glyph fitter owns the actual rewrite; mark this pair so the
      // anti-oscillation guard still applies, then run it after writing.
      applied.push(`${p.id}: glyph-fit text layer ${p.fix.layer} (${p.flags.join(",")})`);
    } else continue;
    repaired.add(key);
  }
  if (applied.length) {
    writeTl(tl);
    if (report.problems.some((p) => p.fix?.kind === "fit_text")) {
      sh(["scripts/fitTextInTimeline.mjs", TL], "fitText");
    }
  }
  return applied;
}

/** Swap the hero of any story scene qaClip found dark/bright/flat for the best unused photo. */
function applyClipFixes(qa) {
  if (actionFor(TIER, "frame_brightness") !== "repair") return [];
  const fixable = qa.problems.filter((p) => /_dark|_bright|flat/.test(p.flags.join(",")));
  if (!fixable.length) return [];
  const photos = readJson(`${analysisDir}/photos.json`).photos;
  const byQual = [...photos].sort((a, b) => b.qualityNorm - a.qualityNorm);
  const tl = readJson(TL);
  const used = new Set(tl.slides.flatMap((s) => [
    ...(s.layers || []).filter((l) => l.type === "image").map((l) => l.path),
    ...(s.images || []),
  ]));
  const applied = [];
  for (const prob of fixable) {
    const key = `${prob.id}:frame`;
    if (repaired.has(key)) continue;
    const slide = tl.slides.find((s) => s.id === prob.id);
    if (!slide || !slide.layers) continue;      // montages have no hero layer to swap
    const hero = slide.layers.find((l) => l.type === "image" && l.motion);
    if (!hero) continue;
    const orient = photos.find((p) => p.file === hero.path)?.orient;
    const repl = byQual.find((p) => p.orient === orient && !used.has(p.file));
    if (!repl) continue;
    applied.push(`${prob.id}: hero ${hero.path} -> ${repl.file} (${prob.flags.join(",")})`);
    hero.path = repl.file; hero.focusX = repl.focusX; hero.focusY = repl.focusY;
    used.add(repl.file);
    repaired.add(key);
  }
  if (applied.length) writeTl(tl);
  return applied;
}

const policyProblems = (problems) => problems.filter((p) => actionFor(TIER, p.check) !== "warn");
const blockingProblems = (problems) => problems.filter((p) => actionFor(TIER, p.check) === "block");

// --- loop ------------------------------------------------------------------
console.log(`[qaLoop] ${TL} — max ${MAX_REVISIONS} revision(s) after the first render.`);

let revisions = 0;
const journal = [];

function writeSummary(manualReview = [], statusOverride = "") {
  const tl = readJson(TL);
  const summary = {
    timeline: TL,
    video: tl.output?.path ?? null,
    revisions,
    maxRevisions: MAX_REVISIONS,
    journal,
    manualReview,
    status: statusOverride || (manualReview.length ? "delivered_with_flags" : "clean"),
  };
  const loopOut = `${analysisDir}/qa/${base}.loop.json`;
  fs.mkdirSync(path.dirname(path.resolve(root, loopOut)), { recursive: true });
  fs.writeFileSync(path.resolve(root, loopOut), JSON.stringify(summary, null, 2));
  appendFeedback({ root, analysisDir, projectId: tl.project?.name || TL, type: "qa_completed",
    recipeId: tl.recipeDecisions?.recipeId || tl.recipeDecisions?.recipe || null, pacing: tl.recipeDecisions?.pacingVariant,
    data: { revisions, openIssues: manualReview.length, clean: !manualReview.length } });
  console.log(
    `\n[qaLoop] ${summary.status} — ${revisions} revision(s), ${manualReview.length} open issue(s). ` +
      `Output: ${summary.video}. Report: ${loopOut}`
  );
}

// PRE-FLIGHT — proxy repairs are free (no video), so they don't spend the budget.
console.log("\n— pre-flight (no render): pacing + hero —");
for (let pass = 1; pass <= PREFLIGHT_SAFETY_CAP; pass++) {
  const preflight = runProxy();
  const applied = applyProxyFixes(preflight);
  if (!applied.length) { console.log(`  pass ${pass}: nothing left to repair (verdict=${preflight.verdict}).`); break; }
  for (const a of applied) console.log(`  pass ${pass} fix: ${a}`);
  journal.push(...applied.map((a) => `preflight: ${a}`));
  // The fix-once rule (repaired, above) means a pass with zero new fixes is the only exit
  // condition that means "actually clean" — hitting the cap instead means real problems
  // are being left unrepaired, which is worth knowing about even though pre-flight is free.
  if (pass === PREFLIGHT_SAFETY_CAP) console.warn(`[qaLoop] pre-flight hit the ${PREFLIGHT_SAFETY_CAP}-pass safety cap while still finding fixes — this timeline may need investigation, not just more passes.`);
}

// Do not spend an encode on a timeline that the tier is forbidden to ship.
// Repairs above get their bounded chance first; unresolved blockers stop here.
const preRenderReport = runProxy();
const preRenderBlockers = blockingProblems(preRenderReport.problems);
if (preRenderBlockers.length) {
  const open = preRenderBlockers.map((p) => `${p.id}[${p.flags.join(",")}]`);
  console.error(`[qaLoop] PRE-RENDER GATE FAILED: ${open.join(" ")}`);
  writeSummary(open, "blocked_pre_render");
  process.exit(1);
}

if (skipRender) {
  console.log("\n[qaLoop] --skip-render: stopping after pre-flight.");
  const rep = runProxy();
  const open = policyProblems(rep.problems).map((p) => `${p.id}[${p.flags.join(",")}]`);
  console.log(`[qaLoop] final proxy verdict: ${rep.verdict} (${rep.problems.length} problem(s) remain).`);
  writeSummary(open);
  // --strict gates in every mode. A pre-flight-only run that leaves manual-review issues
  // open must fail exactly as the render+revise path does below — otherwise --skip-render
  // silently turns a strict gate into a no-op and passes a timeline it should have blocked.
  if (strict && open.length) {
    console.error(`[qaLoop] QUALITY GATE FAILED: ${open.length} issue(s) remain (pre-flight only).`);
    process.exit(1);
  }
  process.exit(0);
}

// RENDER + REVISE
if (skipInitialRender) console.log("  using the render already produced by the render phase.");
else { render(); console.log("  rendered."); }

let manualReview = [];
while (true) {
  const qa = runClip();                       // layer 1: measurable, no AI
  const proxy = runProxy();                   // layer 2: proxies (+ bookend frames now that video exists)
  const open = [
    ...qa.problems.map((p) => `${p.id}[${p.flags.join(",")}]`),
    ...policyProblems(proxy.problems).map((p) => `${p.id}[${p.flags.join(",")}]`),
  ];
  if (!open.length) { manualReview = []; console.log("\n[qaLoop] clean: both QA layers pass."); break; }

  console.log(`\n— QA found ${open.length} issue(s): ${open.join(" ")} —`);
  if (revisions >= MAX_REVISIONS) {
    manualReview = open;
    console.log(`[qaLoop] revision cap (${MAX_REVISIONS}) reached — delivering current cut, flagged for manual review.`);
    break;
  }

  const applied = [...applyClipFixes(qa), ...applyProxyFixes(proxy)];
  if (!applied.length) {
    manualReview = open;
    console.log("[qaLoop] no deterministic fix available for the remaining issues — delivering, flagged for manual review.");
    break;
  }
  revisions++;
  for (const a of applied) console.log(`  revision ${revisions} fix: ${a}`);
  journal.push(...applied.map((a) => `revision ${revisions}: ${a}`));
  render();
  console.log(`  re-rendered (revision ${revisions}/${MAX_REVISIONS}).`);
}

writeSummary(manualReview);
sh(["scripts/generateContactSheet.mjs", TL, "--analysis-dir", analysisDir], "contactSheet");
if (strict && manualReview.length) {
  console.error(`[qaLoop] QUALITY GATE FAILED: ${manualReview.length} issue(s) remain after ${revisions} revision(s).`);
  process.exit(1);
}
