// Phase E / node 11 — the closed QA loop with a HARD revision cap.
//
// Layers, per PIPELINE-V1-VA-LITE.md §11:
//   1. rule-based, no AI   -> qaClip.mjs   (too_dark / too_bright / flat)   [needs the video]
//   2. measurable proxies  -> qaProxy.mjs  (pacing, hero)                    [no video needed]
//   3. the one subjective  -> qaProxy bookend (opening/ending)               [needs video + vision]
//
// Structure follows from what each layer costs:
//
//   PRE-FLIGHT (free)  proxy -> fix -> proxy ... until clean. Pacing and hero
//       need no rendered frames, so these repairs cost nothing and do NOT spend
//       the revision budget. Bounded by PREFLIGHT_PASSES and a fix-once rule.
//   RENDER
//   REVISE (expensive) qaClip + proxy -> fix -> re-render. Each pass here spends
//       one revision. Hard cap --max-revisions (default 2). On exhaustion we
//       DELIVER the current cut and flag it for manual review — never loop.
//
// Every fix is deterministic (node 9's argument): the timeline is generated by
// code from already-guardrailed enums, so what QA finds is mechanical — a
// duration that fights the music, a hero slot holding a weak photo, a scene that
// rendered dark. Code repairs those directly. Re-prompting a model would be
// slower, non-reproducible, and is what makes aesthetic QA loop forever.
//
// Anti-oscillation: a (scene, check) pair is repaired at most once. Changing one
// slide's duration shifts every later slide's start time and therefore its own
// expected duration, so an unbounded "fix everything each pass" would chase its
// own tail. The fix-once rule plus the cap make termination structural.
//
// Usage: node scripts/qaLoop.mjs [--timeline timeline/quoc-nhi-full-v2.json]
//   [--content analysis/photo_content.json] [--max-revisions 2] [--skip-render]
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";

const root = process.cwd();
const node = process.execPath;
const arg = (flag, def) => {
  const i = process.argv.indexOf(flag);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : def;
};

const TL = arg("--timeline", "timeline/quoc-nhi-full-v2.json");
const contentPath = arg("--content", "analysis/photo_content.json");
const MAX_REVISIONS = Number(arg("--max-revisions", "2"));
const PREFLIGHT_PASSES = 3; // free passes; the fix-once rule usually converges in 1
const skipRender = process.argv.includes("--skip-render");

const tlAbs = path.resolve(root, TL);
if (!fs.existsSync(tlAbs)) { console.error(`[qaLoop] FAILED: timeline not found: ${TL}`); process.exit(1); }
const base = path.basename(TL).replace(/\.[^.]+$/, "");
const proxyOut = `analysis/qa/${base}.proxy.json`;
const clipOut = `analysis/qa/${base}.json`;

const readJson = (p) => JSON.parse(fs.readFileSync(path.resolve(root, p), "utf8"));
const writeTl = (tl) => fs.writeFileSync(tlAbs, JSON.stringify(tl, null, 2));

function sh(args, label) {
  const r = spawnSync(node, args, { cwd: root, encoding: "utf8", maxBuffer: 1 << 26 });
  if (r.status !== 0) {
    process.stderr.write((r.stdout || "") + (r.stderr || ""));
    throw new Error(`${label} failed (exit ${r.status})`);
  }
  return r;
}

const runProxy = () => {
  sh(["scripts/qaProxy.mjs", TL, "--content", contentPath, "--out", proxyOut], "qaProxy");
  return readJson(proxyOut);
};
const runClip = () => {
  sh(["scripts/qaClip.mjs", TL, "--out", clipOut], "qaClip");
  return readJson(clipOut);
};
const render = () => {
  const r = spawnSync(node, ["--import", "tsx", "src/index.ts", "--timeline", TL], { cwd: root, encoding: "utf8", maxBuffer: 1 << 26 });
  if (r.status !== 0) {
    console.error((r.stdout || "").split("\n").slice(-8).join("\n") + (r.stderr || ""));
    throw new Error(`render failed (exit ${r.status})`);
  }
};

// --- deterministic fixes ---------------------------------------------------
const repaired = new Set(); // "<sceneId>:<check>" — fix each pair at most once

/** Apply the fixes qaProxy proposed. Returns the list actually applied. */
function applyProxyFixes(report) {
  const tl = readJson(TL);
  const applied = [];
  for (const p of report.problems) {
    if (!p.fix) continue;                       // e.g. hero_not_in_content: needs re-analysis, not a swap
    const key = `${p.id}:${p.check}`;
    if (repaired.has(key)) continue;            // anti-oscillation
    const slide = tl.slides.find((s) => s.id === p.id);
    if (!slide) continue;

    if (p.fix.kind === "set_duration") {
      const from = slide.duration;
      slide.duration = p.fix.to;
      applied.push(`${p.id}: duration ${from}s -> ${p.fix.to}s (${p.flags.join(",")})`);
    } else if (p.fix.kind === "swap_hero") {
      const l = slide.layers?.[p.fix.layer];
      if (!l || l.type !== "image") continue;
      const from = l.path;
      l.path = p.fix.to;
      l.focusX = p.fix.focusX;
      l.focusY = p.fix.focusY;
      applied.push(`${p.id}: hero ${from} -> ${p.fix.to} (${p.flags.join(",")})`);
    } else continue;
    repaired.add(key);
  }
  if (applied.length) writeTl(tl);
  return applied;
}

/** Swap the hero of any story scene qaClip found dark/bright/flat for the best unused photo. */
function applyClipFixes(qa) {
  const fixable = qa.problems.filter((p) => /_dark|_bright|flat/.test(p.flags.join(",")));
  if (!fixable.length) return [];
  const photos = readJson("analysis/photos.json").photos;
  const byQual = [...photos].sort((a, b) => b.qualityNorm - a.qualityNorm);
  const tl = readJson(TL);
  const used = new Set(tl.slides.flatMap((s) => [
    ...(s.layers || []).filter((l) => l.type === "image").map((l) => l.path),
    ...(s.images || []),
  ]));
  const applied = [];
  for (const prob of fixable) {
    const key = `${prob.id}:frame`;
    if (repaired.has(key)) continue;
    const slide = tl.slides.find((s) => s.id === prob.id);
    if (!slide || !slide.layers) continue;      // montages have no hero layer to swap
    const hero = slide.layers.find((l) => l.type === "image" && l.motion);
    if (!hero) continue;
    const orient = photos.find((p) => p.file === hero.path)?.orient;
    const repl = byQual.find((p) => p.orient === orient && !used.has(p.file));
    if (!repl) continue;
    applied.push(`${prob.id}: hero ${hero.path} -> ${repl.file} (${prob.flags.join(",")})`);
    hero.path = repl.file; hero.focusX = repl.focusX; hero.focusY = repl.focusY;
    used.add(repl.file);
    repaired.add(key);
  }
  if (applied.length) writeTl(tl);
  return applied;
}

// --- loop ------------------------------------------------------------------
console.log(`[qaLoop] ${TL} — max ${MAX_REVISIONS} revision(s) after the first render.`);

let revisions = 0;
const journal = [];

// PRE-FLIGHT — proxy repairs are free (no video), so they don't spend the budget.
console.log("\n— pre-flight (no render): pacing + hero —");
for (let pass = 1; pass <= PREFLIGHT_PASSES; pass++) {
  const preflight = runProxy();
  const applied = applyProxyFixes(preflight);
  if (!applied.length) { console.log(`  pass ${pass}: nothing left to repair (verdict=${preflight.verdict}).`); break; }
  for (const a of applied) console.log(`  pass ${pass} fix: ${a}`);
  journal.push(...applied.map((a) => `preflight: ${a}`));
}

if (skipRender) {
  console.log("\n[qaLoop] --skip-render: stopping after pre-flight.");
  const rep = runProxy();
  console.log(`[qaLoop] final proxy verdict: ${rep.verdict} (${rep.problems.length} problem(s) remain).`);
  process.exit(0);
}

// RENDER + REVISE
render();
console.log("  rendered.");

let manualReview = [];
while (true) {
  const qa = runClip();                       // layer 1: measurable, no AI
  const proxy = runProxy();                   // layer 2: proxies (+ bookend frames now that video exists)
  const open = [
    ...qa.problems.map((p) => `${p.id}[${p.flags.join(",")}]`),
    ...proxy.problems.map((p) => `${p.id}[${p.flags.join(",")}]`),
  ];
  if (!open.length) { manualReview = []; console.log("\n[qaLoop] clean: both QA layers pass."); break; }

  console.log(`\n— QA found ${open.length} issue(s): ${open.join(" ")} —`);
  if (revisions >= MAX_REVISIONS) {
    manualReview = open;
    console.log(`[qaLoop] revision cap (${MAX_REVISIONS}) reached — delivering current cut, flagged for manual review.`);
    break;
  }

  const applied = [...applyClipFixes(qa), ...applyProxyFixes(proxy)];
  if (!applied.length) {
    manualReview = open;
    console.log("[qaLoop] no deterministic fix available for the remaining issues — delivering, flagged for manual review.");
    break;
  }
  revisions++;
  for (const a of applied) console.log(`  revision ${revisions} fix: ${a}`);
  journal.push(...applied.map((a) => `revision ${revisions}: ${a}`));
  render();
  console.log(`  re-rendered (revision ${revisions}/${MAX_REVISIONS}).`);
}

const tl = readJson(TL);
const summary = {
  timeline: TL,
  video: tl.output?.path ?? null,
  revisions,
  maxRevisions: MAX_REVISIONS,
  journal,
  manualReview,
  status: manualReview.length ? "delivered_with_flags" : "clean",
};
fs.writeFileSync(path.resolve(root, `analysis/qa/${base}.loop.json`), JSON.stringify(summary, null, 2));
console.log(
  `\n[qaLoop] ${summary.status} — ${revisions} revision(s), ${manualReview.length} open issue(s). ` +
    `Output: ${summary.video}. Report: analysis/qa/${base}.loop.json`
);
