// Phase E / node 11 — the MEASURABLE half of aesthetic QA.
//
// The design problem (PIPELINE-V1-VA-LITE.md §11): "is this video good?" is
// subjective, so an AI judge can neither be validated nor made to converge — it
// re-scores, re-revises, and loops forever. The fix is to replace each subjective
// verdict with a PROXY: a number already present in the pipeline that correlates
// with it, compared against a threshold. Only the one verdict with no numeric
// proxy is left to AI vision.
//
//   "pacing kém"       -> slide duration vs the music's energy over that span
//   "chọn hero sai"    -> the hero slot's Hero Score (node 2) vs the photo pool
//   "mở đầu/kết yếu"   -> the ONLY genuinely subjective one; needs AI vision
//
// Two properties worth keeping:
//   • pacing + hero need NO rendered video — this can run before the render and
//     catch problems without paying for one. Only the bookend check needs frames.
//   • every finding carries a DETERMINISTIC `fix` the loop can apply (node 9's
//     philosophy: the timeline is generated by code from already-guardrailed
//     enums, so failures are mechanical and code repairs them faster and more
//     reliably than re-prompting a model).
//
// This script only MEASURES and PROPOSES. scripts/qaLoop.mjs applies fixes.
//
// Usage: node scripts/qaProxy.mjs <timeline.json> [--music analysis/music/<t>.json]
//   [--content analysis/photo_content.json] [--out analysis/qa/<name>.proxy.json]
//   [--tolerance 0.25] [--hero-margin 0.15] [--strict]
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { makeEnergy, sceneDur, sceneTimes, barLength, fitScale } from "./lib/pacing.mjs";
import { createTextMeasurer } from "./lib/textMeasure.mjs";
import { sliceMusicAnalysis } from "./lib/musicHighlight.mjs";
import { evaluateTier1Quality } from "./lib/tier1QualityGate.mjs";
import { PACING_TOLERANCE, HERO_SWAP_MARGIN, FOCUS_SAFE_MIN, FOCUS_SAFE_MAX, FACE_CONTAIN_MARGIN,
  HIGHLIGHT_MIN_SEC, HIGHLIGHT_MAX_SEC, PHRASE_SNAP_TOLERANCE_SEC, BLACK_FRAME_YAVG, AUDIO_DRIFT_MAX_SEC } from "./lib/rules/thresholds.mjs";

const root = process.cwd();
const arg = (flag, def) => {
  const i = process.argv.indexOf(flag);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : def;
};

const tlPath = process.argv[2];
if (!tlPath || tlPath.startsWith("--")) {
  console.error("Usage: node scripts/qaProxy.mjs <timeline.json> [--content ...] [--strict]");
  process.exit(1);
}
const TOLERANCE = Number(arg("--tolerance", String(PACING_TOLERANCE)));
const HERO_MARGIN = Number(arg("--hero-margin", String(HERO_SWAP_MARGIN)));
// How far into the film the opening title card may sit and still count as the opening
// bookend when its copy echoes on the closing card (a cold-open pushes it off slide 0).
const OPENING_BOOKEND_MAX = 1;
const strict = process.argv.includes("--strict");
// Same rule as qaLoop: the report belongs to the job that owns the timeline, so
// derive `<job>/analysis` from `<job>/timeline/x.json`. A root timeline still
// resolves to plain "analysis".
const siblingAnalysis = path.posix.join(path.dirname(path.dirname(tlPath.replace(/\\/g, "/"))), "analysis");
const analysisDir = arg("--analysis-dir", siblingAnalysis).replace(/\\/g, "/").replace(/\/$/, "");

const tl = JSON.parse(fs.readFileSync(path.resolve(root, tlPath), "utf8"));
const base = path.basename(tlPath).replace(/\.[^.]+$/, "");
const outPath = arg("--out", `${analysisDir}/qa/${base}.proxy.json`);

// --- inputs ----------------------------------------------------------------
// The pacing proxy is defined against the song's energy curve, so with no music
// it has nothing to measure. That disables THAT check — it must not sink the
// report, since hero and bookend are still perfectly measurable (a musicless
// timeline is a normal thing: smoke tests, silent cuts).
const musicTrack = tl.music?.[0]?.path;
const musicJson = arg(
  "--music",
  musicTrack ? `${analysisDir}/music/${path.basename(musicTrack).replace(/\.[^.]+$/, "")}.json` : ""
);
const musicAbs = musicJson ? path.resolve(root, musicJson) : null;
const musicMissing = !musicAbs || !fs.existsSync(musicAbs)
  ? musicTrack
    ? `music analysis not found: ${musicJson} — run: node scripts/analyzeMusic.mjs "${musicTrack}"`
    : "timeline has no music track"
  : null;
const sourceMusic = musicMissing ? null : JSON.parse(fs.readFileSync(musicAbs, "utf8"));
const music = sourceMusic ? sliceMusicAnalysis(sourceMusic, tl.recipeDecisions?.musicEdit || { mode: "full_song" }) : null;

const contentPath = arg("--content", `${analysisDir}/photo_content.json`);
const contentAbs = path.resolve(root, contentPath);
const content = fs.existsSync(contentAbs) ? JSON.parse(fs.readFileSync(contentAbs, "utf8")) : null;
const photosPath = arg("--photos", `${analysisDir}/photos.json`);
const photosAbs = path.resolve(root, photosPath);
const technicalPhotos = fs.existsSync(photosAbs) ? JSON.parse(fs.readFileSync(photosAbs, "utf8")) : null;
const technicalByFile = new Map((technicalPhotos?.photos || []).map((p) => [p.file, p]));

const scenes = sceneTimes(tl.slides);
const problems = [];
const advisories = [];

const photoPaths = (slide) => [
  ...(slide.image ? [slide.image] : []),
  ...(slide.images || []),
  ...(slide.layers || []).filter((l) => l.type === "image" && l.path).map((l) => l.path),
];

// --- deterministic integrity checks ---------------------------------------
const textMeasurer = createTextMeasurer({ root });
const textOverflow = { status: "ran", flagged: 0, unmeasurable: 0, slots: [] };
for (const [slideIndex, slide] of tl.slides.entries()) {
  for (const [index, layer] of (slide.layers || []).entries()) {
    if (layer.type !== "text") continue;
    const measured = textMeasurer.inspect(layer);
    const row = { id: slide.id, layer: index, lines: measured.lines.length,
      widest: measured.widest, blockHeight: measured.blockHeight, error: measured.error, flags: [] };
    if (measured.error) {
      row.flags.push("text_unmeasurable"); textOverflow.unmeasurable++; textOverflow.flagged++;
      problems.push({ id: slide.id, check: "text_overflow", flags: row.flags,
        detail: `text layer ${index} could not be measured: ${measured.error}` });
    } else if (!measured.fits) {
      row.flags.push("text_overflow"); textOverflow.flagged++;
      problems.push({ id: slide.id, check: "text_overflow", flags: row.flags,
        detail: `text layer ${index} measures ${measured.widest.toFixed(0)}x${measured.blockHeight.toFixed(0)} inside ${layer.width}x${layer.height}`,
        fix: { kind: "fit_text", layer: index } });
    }
    textOverflow.slots.push(row);
  }
}
textMeasurer.close();

const captionIntegrity = { status: "ran", flagged: 0, items: [] };
const seenCopy = new Map();
const decorativeFont = /GreatVibes|DancingScript|Italianno|WindSong|Pacifico|Lobster|Charm|MeaCulpa/i;
const vietnamese = /[àáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ]/i;
for (const [slideIndex, slide] of tl.slides.entries()) {
  const items = [
    ...(slide.layers || []).filter((l) => l.type === "text").map((l, index) => ({ text: l.text, font: l.font, where: `layer:${index}` })),
    ...(slide.captions || []).map((c, index) => ({ text: c.text, font: c.font, where: `caption:${index}` })),
  ];
  for (const item of items) {
    const flags = [];
    const value = String(item.text || "").trim();
    if (/\{\{[^}]+\}\}/.test(value)) flags.push("unresolved_token");
    if (/[ÃÄ]|áº|á»|Æ°|Ä‘/.test(value)) flags.push("mojibake");
    if (vietnamese.test(value) && decorativeFont.test(item.font || "") && value.split(/\s+/).length > 3) flags.push("vietnamese_in_decorative_font");
    const normalized = value.toLowerCase().replace(/\s+/g, " ");
    const firstSeen = normalized ? seenCopy.get(normalized) : null;
    // The couple's names on the opening title card, echoed on the closing card, is a
    // deliberate bookend — not a copy defect. The opening title is not always slide 0:
    // a cinematic recipe cold-opens on a text-less photo and puts the names on the NEXT
    // slide, so the opening bookend spans the leading cards, not just index 0.
    const isClosing = slideIndex === tl.slides.length - 1;
    const intentionalBookendEcho = isClosing && firstSeen != null && firstSeen.slideIndex <= OPENING_BOOKEND_MAX;
    if (normalized && firstSeen && !intentionalBookendEcho) flags.push("duplicate_caption");
    else if (normalized) seenCopy.set(normalized, { slideIndex, location: `${slide.id}:${item.where}` });
    const row = { id: slide.id, where: item.where, flags };
    captionIntegrity.items.push(row);
    if (flags.length) {
      captionIntegrity.flagged++;
      problems.push({ id: slide.id, check: "caption_integrity", flags,
        detail: `${item.where} failed caption integrity: ${flags.join(", ")}` });
    }
  }
}

const duplicates = { status: "ran", flagged: 0, pairs: [] };
for (let i = 1; i < tl.slides.length; i++) {
  const previous = new Set(photoPaths(tl.slides[i - 1]));
  const groupOf = (file) => technicalByFile.get(file)?.duplicateGroup;
  const previousGroups = new Set([...previous].map(groupOf).filter(Boolean));
  const repeated = [...new Set(photoPaths(tl.slides[i]).filter((f) =>
    previous.has(f) || (groupOf(f) && previousGroups.has(groupOf(f)))
  ))];
  // The selected hero is deliberately echoed at the two bookends, never in
  // adjacent slides; all adjacent reuse remains a defect.
  if (repeated.length) {
    duplicates.flagged += repeated.length;
    const row = { previous: tl.slides[i - 1].id, current: tl.slides[i].id, files: repeated };
    duplicates.pairs.push(row);
    problems.push({ id: tl.slides[i].id, check: "duplicate_photo", flags: ["adjacent_duplicate"],
      detail: `${repeated.join(", ")} repeats a file or perceptual duplicate from ${tl.slides[i - 1].id}` });
  }
}

const crop = { status: technicalPhotos ? "ran" : "partial", flagged: 0, unscored: 0, layers: [] };
if (!technicalPhotos) crop.reason = `${photosPath} not found; focus bounds checked, face containment skipped`;
for (const slide of tl.slides) {
  for (const [index, layer] of (slide.layers || []).entries()) {
    if (layer.type !== "image" || layer.fit !== "cover") continue;
    const flags = [];
    if ((layer.focusX ?? 0.5) < FOCUS_SAFE_MIN || (layer.focusX ?? 0.5) > FOCUS_SAFE_MAX ||
        (layer.focusY ?? 0.5) < FOCUS_SAFE_MIN || (layer.focusY ?? 0.5) > FOCUS_SAFE_MAX) flags.push("unsafe_focus");
    if (!(layer.width > 0 && layer.height > 0)) flags.push("invalid_crop_box");
    const photo = technicalByFile.get(layer.path);
    const faces = photo?.faces?.length ? photo.faces.map((f) => f.box) : (photo?.faceBoxEstimate ? [photo.faceBoxEstimate] : []);
    let visible = null;
    if (photo?.w > 0 && photo?.h > 0 && layer.width > 0 && layer.height > 0) {
      const sourceAspect = photo.w / photo.h, targetAspect = layer.width / layer.height;
      if (sourceAspect > targetAspect) {
        const width = targetAspect / sourceAspect;
        visible = { x: (1 - width) * (layer.focusX ?? 0.5), y: 0, width, height: 1 };
      } else {
        const height = sourceAspect / targetAspect;
        visible = { x: 0, y: (1 - height) * (layer.focusY ?? 0.5), width: 1, height };
      }
      const face = faces[0];
      if (faces.length) {
        const margin = FACE_CONTAIN_MARGIN;
        const contained = faces.every((box) => box.x >= visible.x - margin && box.y >= visible.y - margin &&
          box.x + box.width <= visible.x + visible.width + margin &&
          box.y + box.height <= visible.y + visible.height + margin);
        if (!contained) flags.push("face_cropped");
      } else crop.unscored++;
    } else crop.unscored++;
    const row = { id: slide.id, layer: index, path: layer.path, visible, faceBoxEstimate: photo?.faceBoxEstimate || null, flags };
    crop.layers.push(row);
    if (flags.length) {
      crop.flagged++;
      const face = photo?.faceBoxEstimate;
      // A proposed focus must satisfy the same safe bounds this check enforces;
      // clamping to 0..1 produced fixes at 0 that were immediately flagged again.
      const clampFocus = (v) => Math.max(FOCUS_SAFE_MIN, Math.min(FOCUS_SAFE_MAX, v));
      const focusX = face && visible?.width < 1
        ? clampFocus((face.x + face.width / 2 - visible.width / 2) / (1 - visible.width)) : 0.5;
      const focusY = face && visible?.height < 1
        ? clampFocus((face.y + face.height / 2 - visible.height / 2) / (1 - visible.height)) : 0.5;
      const hasSafeFocus = (start, size, visibleSize) => {
        if (visibleSize >= 1) return true;
        const travel = 1 - visibleSize;
        const low = (start + size - visibleSize - FACE_CONTAIN_MARGIN) / travel;
        const high = (start + FACE_CONTAIN_MARGIN) / travel;
        return Math.max(low, FOCUS_SAFE_MIN) <= Math.min(high, FOCUS_SAFE_MAX);
      };
      const focusCannotContainFaces = face && visible && (
        !hasSafeFocus(face.x, face.width, visible.width) ||
        !hasSafeFocus(face.y, face.height, visible.height));
      problems.push({ id: slide.id, check: "crop", flags,
        detail: `${layer.path} has an unsafe cover crop/focus or cuts the estimated face region`,
        fix: focusCannotContainFaces
          ? { kind: "set_fit", layer: index, to: "contain" }
          : { kind: "set_focus", layer: index, focusX, focusY } });
    }
  }
}

const tier1Gate = evaluateTier1Quality(tl);
problems.push(...tier1Gate.errors);
advisories.push(...tier1Gate.warnings.map((f) => `[${f.check}] ${f.detail}`));
advisories.push(...tier1Gate.manualReview.map((f) => `[manual-review:${f.check}] ${f.detail}`));

// A slide is a montage when it carries an `images` array (montageScene); the
// last slide is the closing card. Both are paced by rules other than the energy
// curve, so the pacing proxy would be measuring the wrong thing on them.
const kindOf = (s, i) =>
  Array.isArray(s.images) ? "montage" : i === tl.slides.length - 1 ? "closing" : "story";

// --- check 1: pacing -------------------------------------------------------
// The generator picked each duration from the energy at the slide's START.
// Here we re-derive it from the MEAN energy across the span the slide actually
// occupies. They diverge when the song changes under a slide, when the story
// plan's emphasis multiplier fought the music, or when a human edited the file.
const pacing = { status: "skipped", tolerance: TOLERANCE, flagged: 0, scenes: [] };
if (musicMissing) {
  pacing.reason = musicMissing;
  pacing.scenes = scenes.map((sc, i) => ({ id: sc.id, kind: kindOf(tl.slides[i], i), start: sc.start, end: sc.end, dur: sc.dur, flags: [] }));
} else {
  pacing.status = "ran";
  const energy = makeEnergy(music);
  const bar = barLength(music);

  // QA computes the scale ITSELF, from the rendered timeline and the track — it
  // does not read a number the generator wrote down, which would make the check
  // agree with the generator by construction. Montages (bar-locked) and the
  // closing card (a fixed full stop) are excluded, exactly as they are from the
  // per-scene check below.
  const storyScenes = scenes.filter((sc, i) => {
    const k = kindOf(tl.slides[i], i);
    return k !== "montage" && k !== "closing";
  });
  const fixed = scenes
    .filter((sc, i) => {
      const k = kindOf(tl.slides[i], i);
      return k === "montage" || k === "closing";
    })
    .reduce((n, sc) => n + sc.dur, 0);
  const pacingScale = storyScenes.length
    ? fitScale({
        baseDurations: storyScenes.map((sc) => sceneDur(energy.meanOver(sc.start, sc.end))),
        transitions: storyScenes.map((sc, i) => tl.slides[i]?.transition?.duration ?? 0),
        targetDuration: Math.max(1, (music.duration ?? 0) - fixed),
      })
    : 1;
  pacing.scale = +pacingScale.toFixed(3);

  pacing.scenes = scenes.map((sc, i) => {
    const slide = tl.slides[i];
    const kind = kindOf(slide, i);
    const eStart = energy.at(sc.start);
    const eMean = energy.meanOver(sc.start, sc.end);
    const row = {
      id: sc.id,
      kind,
      start: sc.start,
      end: sc.end,
      dur: sc.dur,
      energyStart: +eStart.toFixed(3),
      energyMean: +eMean.toFixed(3),
      flags: [],
    };

    if (kind === "montage") {
      // bar-locked, not energy-locked: report alignment as advice, never a revise trigger
      const off = Math.abs(sc.dur - Math.round(sc.dur / bar) * bar);
      row.barLength = +bar.toFixed(3);
      row.barOffset = +off.toFixed(3);
      if (off > 0.3) advisories.push(`${sc.id}: montage is ${off.toFixed(2)}s off a ${bar.toFixed(2)}s bar (duration clamp, not a defect)`);
      return row;
    }
    if (kind === "closing") return row; // fixed-length card by design

    // The energy curve gives a scene its RHYTHM; the photo budget gives the film
    // its SCALE (see lib/pacing fitScale). QA has to apply both, or it "corrects"
    // every stretched scene back to its unstretched length and quietly undoes the
    // one thing that made the film cover the song — which is exactly what happened:
    // a 200s cut came back out of the QA loop as 124s.
    //
    // The check stays independent all the same. The generator scaled durations it
    // derived from energy at each scene's START; QA re-derives them from the MEAN
    // energy over the span each scene actually occupies, and computes its own k
    // from those. Hand edits, emphasis multipliers and energy drift still show up.
    const expected = +(sceneDur(eMean) * pacingScale).toFixed(2);
    const deviation = (sc.dur - expected) / expected;
    row.expected = expected;
    row.deviation = +deviation.toFixed(3);
    row.energyDrift = +(eMean - eStart).toFixed(3);

    if (Math.abs(deviation) > TOLERANCE) {
      const flag = deviation > 0 ? "too_slow_for_music" : "too_fast_for_music";
      row.flags.push(flag);
      problems.push({
        id: sc.id,
        check: "pacing",
        flags: [flag],
        detail:
          `held ${sc.dur}s over music whose mean energy (${eMean.toFixed(2)}) implies ${expected}s ` +
          `(${(deviation * 100).toFixed(0)}%); energy at its start was ${eStart.toFixed(2)}`,
        fix: { kind: "set_duration", to: expected },
      });
    }
    return row;
  });
  pacing.flagged = pacing.scenes.filter((s) => s.flags.length).length;
}

// --- check 2: hero ---------------------------------------------------------
// Reuses the Hero Score from node 2 rather than re-judging the photo. Gated on
// provenance: with `generatedBy: stub` those scores are placeholders, and
// tuning a threshold against placeholders would produce a threshold that means
// nothing once the real vision model is wired. The schema exposes `generatedBy`
// for exactly this decision.
const hero = { status: "skipped", margin: HERO_MARGIN, flagged: 0, slots: [] };
if (!content) {
  hero.reason = `${contentPath} not found — run scripts/analyzePhotoContent.mjs`;
} else if (content.generatedBy === "stub") {
  hero.reason = "photo_content.generatedBy=stub — Hero Scores are placeholders, not real judgements (set OPENAI_API_KEY and re-run analyzePhotoContent)";
} else {
  hero.status = "ran";
  const pool = new Map(content.photos.map((p) => [p.file, p]));
  const scores = content.photos.map((p) => p.heroScore).sort((a, b) => a - b);
  const median = scores[Math.floor(scores.length / 2)];
  hero.poolMedian = +median.toFixed(3);

  const used = new Set();
  for (const s of tl.slides) {
    for (const l of s.layers || []) if (l.type === "image" && l.path) used.add(l.path);
    for (const f of s.images || []) used.add(f);
  }

  tl.slides.forEach((slide, si) => {
    (slide.layers || []).forEach((l, li) => {
      if (l.type !== "image" || !l.motion) return; // hero slot == the image that moves
      const rec = pool.get(l.path);
      if (!rec) {
        hero.slots.push({ id: slide.id, layer: li, path: l.path, flags: ["hero_not_in_content"] });
        problems.push({
          id: slide.id,
          check: "hero",
          flags: ["hero_not_in_content"],
          detail: `${l.path} is a hero slot but has no Hero Score in ${contentPath} (analysis drift)`,
        });
        hero.flagged++;
        return;
      }
      const row = { id: slide.id, layer: li, path: l.path, heroScore: rec.heroScore, orient: rec.orient, flags: [] };
      if (rec.heroScore < median) {
        const better = content.photos
          .filter((p) => !used.has(p.file) && p.orient === rec.orient && p.heroScore >= rec.heroScore + HERO_MARGIN)
          .sort((a, b) => b.heroScore - a.heroScore)[0];
        if (better) {
          row.flags.push("weak_hero");
          row.suggest = { file: better.file, heroScore: better.heroScore };
          hero.flagged++;
          problems.push({
            id: slide.id,
            check: "hero",
            flags: ["weak_hero"],
            detail:
              `hero ${l.path} scores ${rec.heroScore} (below pool median ${median.toFixed(3)}); ` +
              `unused ${better.file} scores ${better.heroScore}`,
            fix: {
              kind: "swap_hero",
              slide: slide.id,
              layer: li,
              to: better.file,
              focusX: better.focusX ?? 0.5,
              focusY: better.focusY ?? 0.45,
            },
          });
        }
      }
      hero.slots.push(row);
    });
  });
}

// --- check 3: bookend (opening / ending) -----------------------------------
// The one verdict with no numeric proxy. Frame extraction runs for real (and is
// what proves the video is samplable); only the SCORING needs a vision model.
const bookend = { status: "skipped" };
const videoRel = tl.output?.path;
const videoAbs = videoRel ? path.resolve(root, videoRel) : null;
const ffmpeg = process.env.FFMPEG_PATH || "ffmpeg";

function grabFrame(sec, dest) {
  const r = spawnSync(ffmpeg, ["-v", "error", "-y", "-ss", sec.toFixed(2), "-i", videoAbs,
    "-frames:v", "1", "-q:v", "3", dest], { encoding: "utf8" });
  return r.status === 0 && fs.existsSync(dest);
}

const blackFrames = { status: "skipped", flagged: 0, samples: [] };
const audioDrift = { status: "skipped", flagged: 0 };
const musicEdit = { status: "ran", flagged: 0 };
{
  const edit = tl.recipeDecisions?.musicEdit;
  const track = tl.music?.[0];
  if (!edit) {
    musicEdit.status = "skipped";
    musicEdit.reason = "timeline has no musicEdit decision";
  } else {
    Object.assign(musicEdit, { mode: edit.mode, start: edit.start, end: edit.end, duration: edit.duration });
    const invalidRange = !(edit.start >= 0 && edit.end > edit.start && edit.end <= edit.sourceDuration + 0.01);
    const invalidHighlightLength = edit.mode === "highlight" && (edit.duration < HIGHLIGHT_MIN_SEC || edit.duration > HIGHLIGHT_MAX_SEC);
    const contractMismatch = edit.mode === "highlight" && (track?.start !== edit.start || track?.end !== edit.end);
    const phraseTimes = sourceMusic?.phrases?.map((p) => p.time) || [];
    const nearest = (value) => phraseTimes.length ? Math.min(...phraseTimes.map((t) => Math.abs(t - value))) : null;
    musicEdit.startPhraseDrift = nearest(edit.start);
    musicEdit.endPhraseDrift = nearest(edit.end);
    const endsAtTrackEnd = Math.abs(edit.end - edit.sourceDuration) <= 0.05;
    const offPhrase = edit.mode === "highlight" && phraseTimes.length > 0 &&
      (musicEdit.startPhraseDrift > PHRASE_SNAP_TOLERANCE_SEC || (!endsAtTrackEnd && musicEdit.endPhraseDrift > PHRASE_SNAP_TOLERANCE_SEC));
    const flags = [invalidRange && "invalid_music_edit_range", invalidHighlightLength && "invalid_highlight_length",
      contractMismatch && "music_trim_contract_mismatch", offPhrase && "music_edit_off_phrase"].filter(Boolean);
    musicEdit.flagged = flags.length;
    if (flags.length) problems.push({ id: "music_edit", check: "music_edit", flags,
      detail: `music edit ${edit.mode} ${edit.start}s–${edit.end}s against ${edit.sourceDuration}s source` });
  }
}
if (videoAbs && fs.existsSync(videoAbs)) {
  blackFrames.status = "ran";
  for (const sc of scenes) {
    const r = spawnSync(ffmpeg, ["-v", "error", "-ss", sc.mid.toFixed(2), "-i", videoAbs,
      "-frames:v", "1", "-vf", "signalstats,metadata=print:file=-", "-f", "null", "-"],
      { encoding: "utf8", maxBuffer: 1 << 20 });
    const text = `${r.stdout || ""}${r.stderr || ""}`;
    const yavg = Number(text.match(/lavfi\.signalstats\.YAVG=([0-9.]+)/)?.[1]);
    const row = { id: sc.id, at: +sc.mid.toFixed(2), yavg: Number.isFinite(yavg) ? yavg : null, flags: [] };
    if (Number.isFinite(yavg) && yavg < BLACK_FRAME_YAVG) {
      row.flags.push("black_frame"); blackFrames.flagged++;
      problems.push({ id: sc.id, check: "black_frame", flags: row.flags,
        detail: `sample at ${sc.mid.toFixed(2)}s has YAVG ${yavg.toFixed(2)}` });
    }
    blackFrames.samples.push(row);
  }

  audioDrift.status = "ran";
  const probe = process.env.FFPROBE_PATH || "ffprobe";
  const durationOf = (selector) => {
    const r = spawnSync(probe, ["-v", "error", "-select_streams", selector,
      "-show_entries", "stream=duration", "-of", "default=nw=1:nk=1", videoAbs], { encoding: "utf8" });
    return Number((r.stdout || "").trim().split(/\s+/)[0]);
  };
  const videoDuration = durationOf("v:0"), audioDuration = durationOf("a:0");
  audioDrift.videoDuration = Number.isFinite(videoDuration) ? videoDuration : null;
  audioDrift.audioDuration = Number.isFinite(audioDuration) ? audioDuration : null;
  audioDrift.drift = Number.isFinite(videoDuration) && Number.isFinite(audioDuration)
    ? +Math.abs(videoDuration - audioDuration).toFixed(3) : null;
  if (audioDrift.drift != null && audioDrift.drift > AUDIO_DRIFT_MAX_SEC) {
    audioDrift.flagged = 1;
    problems.push({ id: "audio", check: "audio_drift", flags: ["audio_video_duration_mismatch"],
      detail: `audio/video duration differs by ${audioDrift.drift}s` });
  }
} else {
  blackFrames.reason = "rendered video not found";
  audioDrift.reason = "rendered video not found";
}

if (!videoAbs || !fs.existsSync(videoAbs)) {
  bookend.reason = `rendered video not found (${videoRel || "no output.path"}) — bookend needs frames; render first`;
} else {
  const dir = path.resolve(root, `${analysisDir}/qa/frames`);
  fs.mkdirSync(dir, { recursive: true });
  const first = scenes[0], last = scenes[scenes.length - 1];
  const openPng = path.join(dir, `${base}.opening.jpg`);
  const endPng = path.join(dir, `${base}.ending.jpg`);
  const okOpen = grabFrame(first.mid, openPng);
  const okEnd = grabFrame(last.mid, endPng);
  bookend.frames = {
    opening: okOpen ? path.relative(root, openPng).replace(/\\/g, "/") : null,
    ending: okEnd ? path.relative(root, endPng).replace(/\\/g, "/") : null,
    at: { opening: first.mid, ending: last.mid },
  };
  if (!okOpen || !okEnd) bookend.reason = "could not sample opening/ending frames from the video";
  else if (!(process.env.VISION_API_KEY || process.env.OPENAI_API_KEY)) bookend.reason = "no VISION_API_KEY / OPENAI_API_KEY — frames sampled, scoring skipped (this check genuinely needs AI vision)";
  else bookend.reason = "vision scoring not yet wired (frames are ready at bookend.frames)";
}

// --- report ----------------------------------------------------------------
const verdict = problems.length ? "review" : "ok";
const report = {
  timeline: tlPath.replace(/\\/g, "/"),
  video: videoRel ?? null,
  generatedAt: new Date().toISOString(),
  inputs: {
    music: musicJson ? musicJson.replace(/\\/g, "/") : null,
    photoContent: content ? { path: contentPath.replace(/\\/g, "/"), generatedBy: content.generatedBy } : null,
  },
  checks: { pacing, hero, textOverflow, captionIntegrity, duplicates, crop, tier1Gate, blackFrames, audioDrift, musicEdit, bookend },
  advisories,
  problems,
  verdict,
};

fs.mkdirSync(path.dirname(path.resolve(root, outPath)), { recursive: true });
fs.writeFileSync(path.resolve(root, outPath), JSON.stringify(report, null, 2));

const storyN = pacing.scenes.filter((s) => s.kind === "story").length;
const pacingN = pacing.status === "ran" ? `${pacing.flagged} flagged/${storyN} story scenes` : "skipped";
const heroN = hero.status === "ran" ? hero.flagged : "skipped";
console.log(
  `QA-proxy ${base}: verdict=${verdict} — pacing ${pacingN}, hero ${heroN}, bookend ${bookend.status}. -> ${outPath}`
);
for (const p of problems) console.log(`  [${p.check}] ${p.id}: ${p.flags.join(",")} — ${p.detail}`);
for (const a of advisories) console.log(`  (advisory) ${a}`);
if (pacing.status === "skipped") console.log(`  pacing check skipped: ${pacing.reason}`);
if (hero.status === "skipped") console.log(`  hero check skipped: ${hero.reason}`);
if (bookend.status === "skipped") console.log(`  bookend skipped: ${bookend.reason}`);

if (strict && verdict !== "ok") process.exit(1);
