// Phase D / node 9 — VALIDATE → RETRY → FALLBACK orchestrator.
//
// Wraps the director-aware generation (Phase C) in the closed loop the design
// asks for: generate → dry-run validate → on a specific, recognised failure
// apply a specific fix and retry (capped) → if it still won't validate, fall
// back to the Lite (rule-based) pipeline so the customer still gets a video.
//
// WHY the fixes are deterministic, not "ask the AI again": in this architecture
// the timeline is generated by CODE from already-guardrailed director decisions
// (Phase B clamps every effect/transition to the engine enums), so the failures
// that actually reach the engine are mechanical/data, not bad AI enums:
//   • missing photo/asset files (data drift) → prune them and regenerate;
//   • a malformed director artifact (e.g. a hand-edited director_notes.json that
//     bypassed the Phase B guardrail) → drop the director layer and regenerate
//     rule-based (Lite).
// Both are fixed faster and more reliably by code than by a round-trip to the
// model, which is the point of node 9. (If a node ever has the AI write the
// timeline directly, re-prompting on the parsed error would slot in here.)
//
// Engine exit-code contract (src/index.ts): 0 ok · 1 validation · 2 ffmpeg · 99 unknown.
//   1 → parse the error, apply a fix, retry.   2 → infra retry (re-render, same JSON).
//
// Usage: node scripts/renderWithRetry.mjs [--music "music/a thousand years.mp3"]
//   [--director analysis/director_notes.json|none] [--plan analysis/story_plan.json|none]
//   [--out timeline/quoc-nhi-full-v2.json] [--photos analysis/photos.json]
//   [--max-retries 2] [--dry-run-only] [--deliver]
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";

const root = process.cwd();
const node = process.execPath;
const arg = (flag, def) => {
  const i = process.argv.indexOf(flag);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : def;
};
// No default track — see applyStoryTemplate.
const music = arg("--music", "");
if (!music) {
  console.error(`[renderWithRetry] FAILED: --music is required.`);
  process.exit(1);
}
const directorArg = arg("--director", "analysis/director_notes.json");
const planArg = arg("--plan", "analysis/story_plan.json");
const TL = arg("--out", "timeline/quoc-nhi-full-v2.json");
const basePhotos = arg("--photos", "analysis/photos.json");
const maxRetries = Number(arg("--max-retries", "2")) || 2;
const dryRunOnly = process.argv.includes("--dry-run-only");
const deliver = process.argv.includes("--deliver");
// Project-local redirection. Defaults reproduce the pre-project behaviour, so a
// bare `node scripts/renderWithRetry.mjs` still writes exactly where it used to.
const analysisDir = arg("--analysis-dir", "analysis").replace(/\\/g, "/").replace(/\/$/, "");
const videoOut = arg("--output", "output/quoc-nhi-full-v2.mp4");
const projectName = arg("--name", "quoc-nhi-full-v2");
const quality = arg("--quality", "share");
const jobDir = arg("--job-dir", "");
const tierOut = arg("--tier-out", "");
const PRUNED_PHOTOS = `${analysisDir}/photos.pruned.json`;

// --- helpers ---------------------------------------------------------------
function sh(cmd, args) {
  return spawnSync(cmd, args, { cwd: root, encoding: "utf8", maxBuffer: 1 << 26 });
}
/** Run a generation/step script; throws on non-zero so we fail loudly on our own bugs. */
function step(args, label) {
  const r = sh(node, args);
  if (r.status !== 0) {
    process.stderr.write((r.stdout || "") + (r.stderr || ""));
    throw new Error(`${label} failed (exit ${r.status})`);
  }
  return r;
}
/** Run the engine on TL; return {code, out} with stdout+stderr combined for parsing. */
function runEngine(dryRun) {
  const args = ["--import", "tsx", "src/index.ts", "--timeline", TL];
  if (jobDir) args.push("--job-dir", jobDir);
  if (dryRun) args.push("--dry-run");
  const r = sh(node, args);
  return { code: r.status ?? 99, out: (r.stdout || "") + (r.stderr || "") };
}

/** Generate the timeline in the given mode, then auto-fit text. */
function generate(mode, photosFile) {
  const dirFlags =
    mode === "lite"
      ? ["--director", "none", "--plan", "none"]
      : ["--director", directorArg, "--plan", planArg];
  step(
    [
      "scripts/generateStoryClipV2.mjs",
      "--music", music,
      "--out", TL,
      "--photos", photosFile,
      "--analysis-dir", analysisDir,
      "--output", videoOut,
      "--name", projectName,
      "--quality", quality,
      ...dirFlags,
    ],
    "generate"
  );
  step(["scripts/fitTextInTimeline.mjs", TL], "fit-text");
}

/** Pull missing image/background paths out of an engine validation report. */
function parseMissingAssets(out) {
  const paths = new Set();
  const re = /(?:image|background) not found:\s*(.+?)\s*$/gm;
  let m;
  while ((m = re.exec(out))) paths.add(m[1]);
  return [...paths];
}
/** True if the report contains asset misses that pruning photos cannot fix (music/font/overlay/lut). */
function hasUnfixableAssetMiss(out) {
  return /(?:music\[|font not found|overlays\[|color\.lut not found|voiceover not found)/.test(out);
}
/** Extract the human-readable [FAILED] block for logging. */
function failBlock(out) {
  const i = out.indexOf("[FAILED]");
  return i >= 0 ? out.slice(i).trim() : out.trim().split("\n").slice(-6).join("\n");
}

/** Write a pruned photos file: drop the reported-missing files AND any whose file
 *  is absent on disk, so the pool converges to all-existing in a single prune. */
function prunePhotos(photosFile, missing) {
  const abs = path.resolve(root, photosFile);
  const doc = JSON.parse(fs.readFileSync(abs, "utf8"));
  const missingSet = new Set(missing);
  const before = doc.photos.length;
  doc.photos = doc.photos.filter(
    (p) => !missingSet.has(p.file) && fs.existsSync(path.resolve(root, p.file))
  );
  doc.count = doc.photos.length;
  const outAbs = path.resolve(root, PRUNED_PHOTOS);
  fs.writeFileSync(outAbs, JSON.stringify(doc, null, 2));
  console.log(`  fix: pruned ${before - doc.photos.length} missing photo(s) -> ${doc.photos.length} usable (${PRUNED_PHOTOS})`);
  return PRUNED_PHOTOS;
}

/** Make sure the analysis the generator reads actually exists (music + photos),
 *  running the rule-based analyzers if not — so a fresh job or a new track does
 *  not crash the generator mid-loop. Clean exit (not a stack trace) if it can't. */
function ensurePrereqs() {
  const musicName = path.basename(music).replace(/\.[^.]+$/, "");
  const musicJson = path.resolve(root, `${analysisDir}/music/${musicName}.json`);
  if (!fs.existsSync(musicJson)) {
    console.log(`[renderWithRetry] music analysis missing → analyzeMusic "${music}"`);
    const r = sh(node, ["scripts/analyzeMusic.mjs", music, "--out", `${analysisDir}/music/${musicName}.json`]);
    if (r.status !== 0 || !fs.existsSync(musicJson)) {
      console.error(`[renderWithRetry] FAILED: cannot analyze music "${music}" (does the file exist?).`);
      process.exit(1);
    }
  }
  const photosJson = path.resolve(root, basePhotos);
  if (!fs.existsSync(photosJson)) {
    if (basePhotos === `${analysisDir}/photos.json`) {
      console.log("[renderWithRetry] photos analysis missing → analyzePhotos");
      const r = sh(node, ["scripts/analyzePhotos.mjs", "--out", basePhotos]);
      if (r.status !== 0 || !fs.existsSync(photosJson)) {
        console.error("[renderWithRetry] FAILED: cannot analyze photos (is input/ populated?).");
        process.exit(1);
      }
    } else {
      console.error(`[renderWithRetry] FAILED: photos file not found: ${basePhotos}`);
      process.exit(1);
    }
  }
}

/** Real render with infra (exit-2) retry — same JSON, the engine/ffmpeg is the flake. */
function realRender(infraTries = 2) {
  for (let i = 0; i <= infraTries; i++) {
    const r = runEngine(false);
    if (r.code === 0) return 0;
    if (r.code === 2) { console.warn(`  ffmpeg error (exit 2); infra retry ${i + 1}/${infraTries}`); continue; }
    console.error(failBlock(r.out));
    return r.code; // 1/99 shouldn't happen after a clean dry-run, but surface it
  }
  console.error("  render still failing after infra retries (exit 2)");
  return 2;
}

// --- loop ------------------------------------------------------------------
function indent(s) { return s.split("\n").map((l) => "    " + l).join("\n"); }

ensurePrereqs();

const directorPresent =
  directorArg !== "none" && fs.existsSync(path.resolve(root, directorArg));
let mode = directorPresent ? "director" : "lite";
let photosFile = basePhotos;
let lastFail = "";
const maxAttempts = maxRetries + 1;

console.log(
  `[renderWithRetry] start — mode=${mode}, maxAttempts=${maxAttempts}, ` +
    `${dryRunOnly ? "dry-run only" : "validate then render"}.`
);

let outcome = null;
try {
  for (let attempt = 1; attempt <= maxAttempts && !outcome; attempt++) {
    console.log(`\n— attempt ${attempt}/${maxAttempts} (mode: ${mode}) —`);
    generate(mode, photosFile);
    const res = runEngine(true); // dry-run validate

    if (res.code === 0) {
      console.log("  validation OK.");
      if (dryRunOnly) { outcome = { code: 0, how: `${mode}, validated (dry-run only)` }; break; }
      const rc = realRender();
      outcome = rc === 0
        ? { code: 0, how: `${mode}, rendered` }
        : { code: rc, how: `render failed (exit ${rc})` };
      break;
    }

    // validation (or unknown) failure — choose a specific fix
    lastFail = failBlock(res.out);
    console.warn(`  validation FAILED (exit ${res.code}):\n${indent(lastFail)}`);
    const missing = parseMissingAssets(res.out);

    if (missing.length && !hasUnfixableAssetMiss(res.out) && attempt < maxAttempts) {
      photosFile = prunePhotos(photosFile, missing);
      continue; // retry same mode with a clean photo pool
    }
    if (mode === "director" && attempt < maxAttempts) {
      console.warn("  fix: dropping the director layer → falling back to Lite (rule-based).");
      mode = "lite";
      continue;
    }
    // nothing left to try
    break;
  }
} catch (e) {
  // A generation step threw (e.g. a corrupt input the generator can't parse).
  console.error(`\n[renderWithRetry] FAILED (generation error): ${e instanceof Error ? e.message : String(e)}`);
  process.exit(1);
}

if (!outcome) {
  console.error(
    `\n[renderWithRetry] FAILED after ${maxAttempts} attempt(s) — needs manual review. Last error:\n${indent(lastFail)}`
  );
  process.exit(1);
}
if (outcome.code !== 0) {
  console.error(`\n[renderWithRetry] ${outcome.how}`);
  process.exit(outcome.code);
}
// Node 12. `mode` here is the mode of the attempt that actually succeeded — the
// fallback may have swapped director→lite mid-loop. Delivery cannot infer that
// from the timeline, so the loop that lived through it hands the tier over.
if (deliver && !dryRunOnly) {
  console.log(`\n[renderWithRetry] delivering (tier=${mode})…`);
  const r = sh(node, ["scripts/deliver.mjs", TL, "--tier", mode, "--analysis-dir", analysisDir]);
  process.stdout.write(r.stdout || "");
  if (r.status !== 0) {
    process.stderr.write(r.stderr || "");
    console.error("[renderWithRetry] FAILED: the render succeeded but delivery did not.");
    process.exit(1);
  }
}

// The tier of the attempt that actually survived. An orchestrator used to recover
// this by regex-scraping the line below, which silently degraded to "unknown" the
// day the log wording changed. State it as data instead of as prose.
if (tierOut) {
  fs.mkdirSync(path.dirname(path.resolve(root, tierOut)), { recursive: true });
  fs.writeFileSync(path.resolve(root, tierOut), JSON.stringify({ tier: mode, decidedAt: new Date().toISOString() }, null, 2) + "\n");
}

const outPath = dryRunOnly ? TL : (JSON.parse(fs.readFileSync(path.resolve(root, TL), "utf8")).output?.path ?? TL);
console.log(`\n[renderWithRetry] SUCCESS — ${outcome.how}. Output: ${outPath}`);
