/**
 * Every piece of copy the web app shows, in both languages side by side.
 *
 * One file with `{ vi, en }` per key rather than one file per locale: the two
 * languages can't silently drift out of sync, because a key with only one
 * language is a type error rather than a blank spot on a page nobody opened.
 *
 * `{name}` placeholders are filled in by `translate`. Keys ending `_one` /
 * `_other` are plural variants picked from `params.count` — English needs the
 * distinction, Vietnamese doesn't, so the two Vietnamese strings are identical
 * on purpose.
 */
const entries = {
  // ── Shared vocabulary ───────────────────────────────────────────────────
  "common.refresh": { vi: "Làm mới", en: "Refresh" },
  "common.cancel": { vi: "Huỷ", en: "Cancel" },
  "common.back": { vi: "Quay lại", en: "Back" },
  "common.continue": { vi: "Tiếp tục", en: "Continue" },
  "common.retry": { vi: "Thử lại", en: "Retry" },
  "common.dismiss": { vi: "Bỏ qua", en: "Dismiss" },
  "common.close": { vi: "Đóng", en: "Close" },
  "common.open": { vi: "Mở", en: "Open" },
  "common.delete": { vi: "Xoá", en: "Delete" },
  "common.download": { vi: "Tải về", en: "Download" },
  "common.downloading": { vi: "Đang tải về…", en: "Downloading…" },
  "common.saving": { vi: "Đang lưu…", en: "Saving…" },
  "common.confirm": { vi: "Xác nhận", en: "Confirm" },
  "common.done": { vi: "Xong", en: "Done" },
  "common.loading": { vi: "Đang tải…", en: "Loading…" },
  "common.selected": { vi: "Đã chọn", en: "Selected" },
  "common.recommended": { vi: "Nên chọn", en: "Recommended" },
  "common.optional": { vi: "(không bắt buộc)", en: "(optional)" },
  "common.requiredFields": { vi: "Trường bắt buộc", en: "Required fields" },
  "common.openNavigation": { vi: "Mở menu điều hướng", en: "Open navigation" },
  "common.closeNavigation": { vi: "Đóng menu điều hướng", en: "Close navigation" },
  "common.studio": { vi: "Studio", en: "Studio" },
  "common.notSet": { vi: "Chưa đặt", en: "Not set" },
  "common.notApplicable": { vi: "Không áp dụng", en: "Not applicable" },
  "common.none": { vi: "Không có", en: "None" },
  "common.unknown": { vi: "không rõ", en: "unknown" },
  "common.missing": { vi: "thiếu", en: "missing" },
  "common.pending": { vi: "Chờ", en: "Pending" },
  "common.stale": { vi: "Đã cũ", en: "Stale" },
  "common.ready": { vi: "Sẵn sàng", en: "Ready" },
  "common.review": { vi: "Xem lại", en: "Review" },
  "common.words": { vi: "từ", en: "words" },
  "common.language": { vi: "Ngôn ngữ", en: "Language" },
  "common.switchLanguage": { vi: "Đổi ngôn ngữ", en: "Switch language" },

  // ── Brand ───────────────────────────────────────────────────────────────
  "brand.tagline": { vi: "Khoảnh khắc lay động", en: "Moments That Move" },

  // ── Project status ──────────────────────────────────────────────────────
  "status.not_started": { vi: "Chưa bắt đầu", en: "Not started" },
  "status.running": { vi: "Đang chạy", en: "Running" },
  "status.completed": { vi: "Hoàn tất", en: "Completed" },
  "status.completed_with_warning": { vi: "Hoàn tất kèm cảnh báo", en: "Completed with warnings" },
  "status.failed": { vi: "Thất bại", en: "Failed" },
  "status.paused": { vi: "Tạm dừng", en: "Paused" },
  "status.invalid": { vi: "Dữ liệu lỗi", en: "Invalid data" },
  // A queued job — a job-only state, so it has no ProjectStatus counterpart.
  "status.pending": { vi: "Đang xếp hàng", en: "Queued" },

  // ── Pipeline phases ─────────────────────────────────────────────────────
  "phase.validate": { vi: "Kiểm tra", en: "Checks" },
  "phase.analyze": { vi: "Phân tích", en: "Media" },
  "phase.plan": { vi: "Câu chuyện", en: "Story" },
  "phase.build": { vi: "Dựng", en: "Edit" },
  "phase.render": { vi: "Kết xuất", en: "Video" },
  "phase.qa": { vi: "Chất lượng", en: "Quality" },
  "phase.deliver": { vi: "Bàn giao", en: "Delivery" },
  "phaseLong.validate": { vi: "Đang kiểm tra dự án", en: "Validating project" },
  "phaseLong.analyze": { vi: "Đang phân tích ảnh và nhạc", en: "Analyzing media" },
  "phaseLong.plan": { vi: "Đang lên câu chuyện", en: "Planning the story" },
  "phaseLong.build": { vi: "Đang dựng timeline", en: "Building the timeline" },
  "phaseLong.render": { vi: "Đang kết xuất phim", en: "Rendering the film" },
  "phaseLong.qa": { vi: "Đang kiểm tra chất lượng", en: "Checking quality" },
  "phaseLong.deliver": { vi: "Đang chuẩn bị bàn giao", en: "Preparing delivery" },

  // ── Project setting values ──────────────────────────────────────────────
  "tier.template": { vi: "Mẫu có sẵn", en: "Template" },
  "tier.lite": { vi: "Lite", en: "Lite" },
  "tier.premium": { vi: "Premium", en: "Premium" },
  "quality.draft": { vi: "Nháp", en: "Draft" },
  "quality.share": { vi: "Chia sẻ", en: "Share" },
  "quality.high": { vi: "Cao", en: "High" },
  "quality.master": { vi: "Master", en: "Master" },
  "sequence.editorial": { vi: "Biên tập", en: "Editorial" },
  "sequence.chronological": { vi: "Theo thời gian", en: "Chronological" },
  "musicMode.auto": { vi: "Tự động", en: "Auto" },
  "musicMode.highlight": { vi: "Đoạn cao trào", en: "Highlight" },
  "musicMode.full_song": { vi: "Trọn bài", en: "Full song" },
  "lang.vi": { vi: "Tiếng Việt", en: "Vietnamese" },
  "lang.en": { vi: "Tiếng Anh", en: "English" },

  // ── App shell ───────────────────────────────────────────────────────────
  "app.openingProject": { vi: "Đang mở dự án…", en: "Opening project…" },
  "app.newFilm": { vi: "Phim mới", en: "New film" },
  "nav.dashboard": { vi: "Tổng quan", en: "Dashboard" },
  "nav.projects": { vi: "Dự án", en: "Projects" },
  "nav.recipes": { vi: "Thư viện phong cách", en: "Recipe Library" },
  "nav.billing": { vi: "Gói & thanh toán", en: "Plans & billing" },
  "nav.changePassword": { vi: "Đổi mật khẩu", en: "Change password" },
  "nav.incidents": { vi: "Sự cố kỹ thuật", en: "Technical incidents" },
  "nav.signOut": { vi: "Đăng xuất", en: "Sign out" },

  // Project pickers reached by deep link without a project selected.
  "route.assets.title": { vi: "Ảnh & nhạc", en: "Assets" },
  "route.assets.description": { vi: "Chọn một dự án để quản lý ảnh và nhạc.", en: "Choose a project to manage photos and music." },
  "route.director.title": { vi: "AI Director", en: "AI Director" },
  "route.director.description": { vi: "Chọn một dự án để định hướng câu chuyện.", en: "Choose a project to shape its story direction." },
  "route.timeline.title": { vi: "Timeline", en: "Timeline" },
  "route.timeline.description": { vi: "Chọn một dự án để xem và sửa mạch cảnh.", en: "Choose a project to inspect and edit its scene flow." },
  "route.render.title": { vi: "Hàng đợi kết xuất", en: "Render queue" },
  "route.render.description": { vi: "Chọn một dự án để chạy hoặc theo dõi kết xuất.", en: "Choose a project to run or monitor rendering." },

  // ── Dashboard ───────────────────────────────────────────────────────────
  "dashboard.welcome": { vi: "Chào mừng trở lại", en: "Welcome back" },
  "dashboard.createFilm": { vi: "Tạo phim mới", en: "Create new film" },
  "dashboard.checkoutSuccess": { vi: "Đã gửi thanh toán — gói của bạn sẽ được cập nhật ngay khi nhà cung cấp thanh toán xác nhận.", en: "Payment submitted — your plan will update as soon as the payment provider confirms it." },
  "dashboard.checkoutCancelled": { vi: "Thanh toán đã bị huỷ — không có khoản nào bị trừ.", en: "Checkout was cancelled — no charge was made." },
  "dashboard.issuesTitle_one": { vi: "1 thư mục dự án không mở được", en: "1 project folder can’t be opened" },
  "dashboard.issuesTitle_other": { vi: "{count} thư mục dự án không mở được", en: "{count} project folders can’t be opened" },
  "dashboard.issuesDetail": { vi: "Chúng được liệt kê bên dưới và trong trang Dự án, kèm lý do của từng thư mục.", en: "They are listed below and on the Projects page, with what is wrong with each." },
  "dashboard.reviewIssues_one": { vi: "Xem lỗi", en: "Review issue" },
  "dashboard.reviewIssues_other": { vi: "Xem các lỗi", en: "Review issues" },
  "dashboard.issueTitle": { vi: "{id}: không mở được", en: "{id}: can’t be opened" },
  "dashboard.updatedAt": { vi: "Cập nhật {date}", en: "Updated {date}" },
  "dashboard.loadingHero": { vi: "Đang tải dự án nổi bật", en: "Loading featured project" },
  "dashboard.openProject": { vi: "Mở dự án", en: "Open project" },
  "dashboard.noProjects": { vi: "Chưa có dự án nào", en: "No projects yet" },
  "dashboard.noProjectsDetail": { vi: "Tạo một phim mới để bắt đầu.", en: "Create a new film to begin." },
  "dashboard.metric.projects": { vi: "Dự án", en: "Projects" },
  "dashboard.metric.projectsDetail": { vi: "Tất cả thư mục dự án", en: "All project folders" },
  "dashboard.metric.running": { vi: "Đang chạy", en: "Running" },
  "dashboard.metric.runningDetail": { vi: "Công việc đang chạy trong pipeline", en: "Active pipeline jobs" },
  "dashboard.metric.paused": { vi: "Tạm dừng", en: "Paused" },
  "dashboard.metric.pausedDetail": { vi: "Đang chờ một quyết định", en: "Waiting for a decision" },
  "dashboard.metric.completed": { vi: "Hoàn tất", en: "Completed" },
  "dashboard.metric.completedDetail": { vi: "Đã bàn giao hoặc đã xong", en: "Delivered or finished" },
  "dashboard.pipelineProgress": { vi: "Tiến độ pipeline", en: "Pipeline progress" },
  "dashboard.lastProgress": { vi: "Tiến độ gần nhất", en: "Last progress" },
  "dashboard.updated": { vi: "Cập nhật", en: "Updated" },
  "dashboard.recentProjects": { vi: "Dự án gần đây", en: "Recent projects" },
  "dashboard.loadingProjects": { vi: "Đang tải thư mục dự án…", en: "Loading project folders…" },
  "dashboard.orderedByUpdate": { vi: "Sắp theo lần cập nhật gần nhất", en: "Ordered by latest job update" },
  "dashboard.viewAll": { vi: "Xem tất cả", en: "View all" },
  "dashboard.noRecentProjects": { vi: "Chưa có dự án gần đây.", en: "No recent projects." },
  "dashboard.needsAttention": { vi: "Cần chú ý", en: "Needs attention" },
  "dashboard.needsAttentionDetail": { vi: "Những dự án có thể cần quyết định hoặc cần sửa", en: "Projects that may need a decision or fix" },
  "dashboard.andMore": { vi: "và {count} mục nữa", en: "and {count} more" },
  "dashboard.allClear": { vi: "Không có gì cần chú ý", en: "Nothing needs attention" },
  "dashboard.allClearDetail": { vi: "Không có dự án nào tạm dừng, thất bại hay lỗi dữ liệu.", en: "No paused, failed, or invalid projects." },

  // ── Sign in / register ──────────────────────────────────────────────────
  "login.welcome": { vi: "Chào mừng trở lại. Những câu chuyện của bạn đang đợi.", en: "Welcome back. Your stories are waiting." },
  "login.registerIntro": { vi: "Tạo tài khoản để bắt đầu kể câu chuyện của bạn.", en: "Create an account to begin crafting your story." },
  "login.username": { vi: "Tên đăng nhập", en: "Username" },
  "login.usernameHint": { vi: "Dùng chữ thường, số hoặc dấu gạch ngang", en: "Use lowercase letters, numbers, or hyphens" },
  "login.password": { vi: "Mật khẩu", en: "Password" },
  "login.confirmPassword": { vi: "Xác nhận mật khẩu", en: "Confirm password" },
  "login.showPassword": { vi: "Hiện mật khẩu", en: "Show password" },
  "login.hidePassword": { vi: "Ẩn mật khẩu", en: "Hide password" },
  "login.showConfirmPassword": { vi: "Hiện mật khẩu xác nhận", en: "Show confirm password" },
  "login.hideConfirmPassword": { vi: "Ẩn mật khẩu xác nhận", en: "Hide confirm password" },
  "login.passwordsDoNotMatch": { vi: "Mật khẩu không khớp", en: "Passwords do not match" },
  "login.unableToSignIn": { vi: "Không đăng nhập được", en: "Unable to sign in" },
  "login.unableToRegister": { vi: "Không tạo được tài khoản", en: "Unable to create account" },
  "login.signIn": { vi: "Đăng nhập", en: "Sign in" },
  "login.signingIn": { vi: "Đang đăng nhập…", en: "Signing in…" },
  "login.createAccount": { vi: "Tạo tài khoản", en: "Create account" },
  "login.creatingAccount": { vi: "Đang tạo tài khoản…", en: "Creating account…" },
  "login.toSignIn": { vi: "Đã có tài khoản? Đăng nhập", en: "Already have an account? Sign in" },
  "login.toRegister": { vi: "Chưa có tài khoản? Tạo mới", en: "Need an account? Create one" },
  "login.or": { vi: "hoặc", en: "or" },
  "login.browseGallery": { vi: "Xem các phim được chia sẻ", en: "Browse shared films" },

  // ── Change password ─────────────────────────────────────────────────────
  "password.title": { vi: "Đổi mật khẩu", en: "Change password" },
  "password.intro": { vi: "Nhập mật khẩu hiện tại trước khi chọn mật khẩu mới.", en: "Enter your current password before choosing a new one." },
  "password.current": { vi: "Mật khẩu hiện tại", en: "Current password" },
  "password.new": { vi: "Mật khẩu mới", en: "New password" },
  "password.confirm": { vi: "Xác nhận mật khẩu mới", en: "Confirm new password" },
  "password.show": { vi: "Hiện {field}", en: "Show {field}" },
  "password.hide": { vi: "Ẩn {field}", en: "Hide {field}" },
  "password.mismatch": { vi: "Mật khẩu mới không khớp", en: "New passwords do not match" },
  "password.failed": { vi: "Không đổi được mật khẩu", en: "Unable to change password" },
  "password.success": { vi: "Đã đổi mật khẩu thành công.", en: "Password changed successfully." },
  "password.changing": { vi: "Đang đổi mật khẩu…", en: "Changing password…" },

  // ── Projects page ───────────────────────────────────────────────────────
  "projects.title": { vi: "Dự án", en: "Projects" },
  "projects.issuesTitle_one": { vi: "1 thư mục trong workspace này không phải dự án dùng được", en: "1 folder in this workspace isn’t a usable project" },
  "projects.issuesTitle_other": { vi: "{count} thư mục trong workspace này không phải dự án dùng được", en: "{count} folders in this workspace aren’t usable projects" },
  "projects.empty": { vi: "Chưa có dự án nào", en: "No projects yet" },
  "projects.emptyDetail": { vi: "Tạo một phim để mở workspace dự án đầu tiên.", en: "Create a film to start the first project workspace." },
  "projects.column.project": { vi: "Dự án", en: "Project" },
  "projects.column.tier": { vi: "Gói", en: "Tier" },
  "projects.column.phase": { vi: "Giai đoạn", en: "Phase" },
  "projects.column.status": { vi: "Trạng thái", en: "Status" },
  "projects.column.progress": { vi: "Tiến độ", en: "Progress" },
  "projects.column.updated": { vi: "Cập nhật", en: "Updated" },
  "projects.cancelJob": { vi: "Dừng {name}", en: "Cancel {name}" },
  "projects.deleteProject": { vi: "Xoá {name}", en: "Delete {name}" },
  "projects.loadingList": { vi: "Đang tải danh sách dự án", en: "Loading projects" },
  "projects.delete.title": { vi: "Xoá dự án", en: "Delete project" },
  // Split around the project name so it can stay bold in the markup — the two
  // languages put the name in the same position, so a prefix/suffix pair works
  // for both without embedding HTML in a translated string.
  "projects.delete.warningBefore": { vi: "Thao tác này xoá vĩnh viễn ", en: "This permanently deletes " },
  "projects.delete.warningAfter": { vi: " cùng toàn bộ ảnh, bản kết xuất và tệp dự án. Không thể hoàn tác.", en: " and all of its photos, renders, and project files. This cannot be undone." },
  "projects.delete.confirmBefore": { vi: "Gõ ", en: "Type " },
  "projects.delete.confirmAfter": { vi: " để xác nhận", en: " to confirm" },
  "projects.delete.deleting": { vi: "Đang xoá…", en: "Deleting…" },

  // ── Intake wizard ───────────────────────────────────────────────────────
  "intake.eyebrow": { vi: "Tạo phim mới", en: "Create new film" },
  "intake.title": { vi: "Khởi tạo dự án", en: "Project intake" },
  "intake.backToDashboard": { vi: "Về trang tổng quan", en: "Back to dashboard" },
  "intake.previousStep": { vi: "Bước trước", en: "Previous step" },
  "intake.progressNav": { vi: "Tiến trình thiết lập dự án", en: "Project setup progress" },
  "intake.stepCounter": { vi: "Bước {current} / {total}", en: "Step {current} of {total}" },
  "intake.step.details": { vi: "Thông tin", en: "Details" },
  "intake.step.direction": { vi: "Định hướng", en: "Direction" },
  "intake.step.output": { vi: "Đầu ra", en: "Output" },
  "intake.step.completed": { vi: "Đã xong: ", en: "Completed: " },
  "intake.step.locked": { vi: "Chưa mở: ", en: "Not yet available: " },
  "intake.step.current": { vi: "Bước hiện tại: ", en: "Current step: " },
  "intake.details.title": { vi: "Kể cho chúng tôi về cặp đôi", en: "Tell us about the couple" },
  "intake.details.description": { vi: "Thiết lập thông tin dự án trước khi thêm ảnh và nhạc.", en: "Set up the project identity before adding media." },
  "intake.field.name": { vi: "Tên dự án", en: "Project name" },
  "intake.field.namePlaceholder": { vi: "Linh & Nam — Phim cưới", en: "Linh & Nam — Wedding Film" },
  "intake.field.nameRequired": { vi: "Hãy nhập tên dự án.", en: "Enter a project name." },
  "intake.field.bride": { vi: "Cô dâu", en: "Bride" },
  "intake.field.brideRequired": { vi: "Hãy nhập tên cô dâu.", en: "Enter the bride's name." },
  "intake.field.groom": { vi: "Chú rể", en: "Groom" },
  "intake.field.groomRequired": { vi: "Hãy nhập tên chú rể.", en: "Enter the groom's name." },
  "intake.field.videoLanguage": { vi: "Ngôn ngữ trong phim", en: "Video language" },
  "intake.field.videoLanguageHint": { vi: "Dùng cho lời dẫn, phụ đề và prompt do AI tạo.", en: "Used for AI-generated narration, captions, and text prompts." },
  "intake.sequence.legend": { vi: "Thứ tự ảnh", en: "Photo sequence" },
  "intake.sequence.hint": { vi: "Chọn cách sắp xếp ảnh trong phim hoàn chỉnh.", en: "Choose how photos will be arranged in the finished film." },
  "intake.sequence.editorialDetail": { vi: "Dựng câu chuyện hình ảnh mạnh nhất dựa trên cảm xúc, khoảnh khắc và chất lượng ảnh.", en: "Builds the strongest visual story from mood, moments, and image quality." },
  "intake.sequence.chronologicalDetail": { vi: "Giữ nguyên thứ tự tải lên để theo dõi cả ngày từ đầu đến cuối.", en: "Keeps photos in upload order to follow the day from start to finish." },
  "intake.direction.title": { vi: "Chọn hướng đạo diễn", en: "Choose the directing path" },
  "intake.direction.description": { vi: "So sánh thời gian hoàn thành và độ sâu sáng tạo, rồi chọn hướng phù hợp cho phim này.", en: "Compare turnaround and creative depth, then choose the path that fits this film." },
  "intake.tier.templateDescription": { vi: "Nhanh, ổn định, dựng theo một công thức đã được kiểm chứng.", en: "Fast, deterministic, and built from a proven recipe." },
  "intake.tier.templateTurnaround": { vi: "Nhanh nhất", en: "Fastest" },
  "intake.tier.templateDepth": { vi: "Định hướng sáng tạo cố định", en: "Fixed creative direction" },
  "intake.tier.liteDescription": { vi: "Câu chuyện có AI hỗ trợ, theo lộ trình sáng tạo tinh gọn.", en: "AI-assisted story with a streamlined creative path." },
  "intake.tier.liteTurnaround": { vi: "Nhanh", en: "Fast" },
  "intake.tier.liteDepth": { vi: "Câu chuyện có AI hỗ trợ", en: "AI-assisted story" },
  "intake.tier.premiumDescription": { vi: "Toàn bộ lựa chọn của AI Director, quyết định về nhạc và kiểm tra chất lượng nâng cao.", en: "Full AI Director choices, music decisions, and advanced QA." },
  "intake.tier.premiumTurnaround": { vi: "Chi tiết nhất", en: "Most detailed" },
  "intake.tier.premiumDepth": { vi: "Toàn quyền sáng tạo", en: "Full creative control" },
  "intake.creditNote": { vi: "Mọi hướng đều tốn một lượt kết xuất — hãy chọn theo tốc độ và mức độ bạn muốn can thiệp sáng tạo.", en: "Every path costs one render credit — pick on turnaround and how much creative control you want." },
  "intake.recipe.title": { vi: "Chọn một phong cách", en: "Select a recipe" },
  "intake.recipe.description": { vi: "Bắt buộc chọn một phong cách. Tìm theo tên, cảm xúc hoặc mục đích sử dụng.", en: "A recipe is required. Search by name, mood, or intended use." },
  "intake.recipe.loading": { vi: "Đang tải danh sách phong cách…", en: "Loading recipes…" },
  "intake.recipe.search": { vi: "Tìm phong cách", en: "Search recipes" },
  "intake.recipe.filterByMood": { vi: "Lọc phong cách theo cảm xúc", en: "Filter recipes by mood" },
  "intake.recipe.allMoods": { vi: "Mọi cảm xúc", en: "All moods" },
  "intake.recipe.noMatches": { vi: "Không có phong cách nào khớp bộ lọc.", en: "No recipes match those filters." },
  "intake.recipe.mostVersatile": { vi: "Linh hoạt nhất", en: "Most versatile" },
  "intake.recipe.anyPhotoCount": { vi: "Mọi số lượng ảnh", en: "Any photo count" },
  "intake.recipe.bestPhotoFit": { vi: "Hợp với ảnh", en: "Best photo fit" },
  "intake.recipe.bestStoryFit": { vi: "Hợp với câu chuyện", en: "Best story fit" },
  "intake.recipe.bestMusicFit": { vi: "Hợp với nhạc", en: "Best music fit" },
  "intake.brief.title": { vi: "Chỉ dẫn cho đạo diễn", en: "Director instructions" },
  "intake.brief.description": { vi: "Mô tả vai trò, câu chuyện, mạch cảm xúc, ngôn ngữ hình ảnh, âm nhạc và mọi điều AI Director phải tuân theo.", en: "Describe the role, story, emotional arc, visual language, music, and anything the AI Director must follow." },
  "intake.brief.placeholder": { vi: "Hãy kể cho StoReel câu chuyện bạn muốn tạo…", en: "Tell StoReel the story you want to create…" },
  "intake.output.title": { vi: "Đầu ra và xác nhận", en: "Output and confirmation" },
  "intake.output.description": { vi: "Xem lại thoả thuận dự án. Việc tải ảnh và nhạc diễn ra sau khi tạo.", en: "Review the project contract. Media upload happens after creation." },
  "intake.output.settings": { vi: "Thiết lập đầu ra", en: "Output settings" },
  "intake.output.quality": { vi: "Chất lượng", en: "Quality" },
  "intake.output.musicMode": { vi: "Chế độ nhạc", en: "Music mode" },
  "intake.contract.title": { vi: "Thoả thuận dự án", en: "Project contract" },
  "intake.contract.project": { vi: "Dự án", en: "Project" },
  "intake.contract.couple": { vi: "Cặp đôi", en: "Couple" },
  "intake.contract.tier": { vi: "Gói", en: "Tier" },
  "intake.contract.recipe": { vi: "Phong cách", en: "Recipe" },
  "intake.contract.language": { vi: "Ngôn ngữ", en: "Language" },
  "intake.contract.sequence": { vi: "Thứ tự ảnh", en: "Sequence" },
  "intake.selectRecipeToContinue": { vi: "Chọn một phong cách để tiếp tục với gói Mẫu có sẵn.", en: "Select a recipe to continue with Template." },
  "intake.create": { vi: "Tạo dự án", en: "Create project" },
  "intake.creating": { vi: "Đang tạo…", en: "Creating…" },

  // ── Project workspace (AssetsPage) ──────────────────────────────────────
  "workspace.eyebrow": { vi: "Workspace dự án", en: "Project workspace" },
  "workspace.workflowNav": { vi: "Quy trình làm phim", en: "Film workflow" },
  "workspace.swipeHint": { vi: "Bước {current} / {total} · Vuốt để xem tất cả các bước →", en: "Step {current} of {total} · Swipe to see all steps →" },
  "workspace.stepCounter": { vi: "Bước {current} / {total}", en: "Step {current} of {total}" },
  "workspace.loadingMedia": { vi: "Đang tải ảnh và nhạc của dự án", en: "Loading project media" },
  "workspace.step.setup": { vi: "Thiết lập", en: "Setup" },
  "workspace.step.media": { vi: "Ảnh & nhạc", en: "Media" },
  "workspace.step.direct": { vi: "Đạo diễn & sửa", en: "Direct & Edit" },
  "workspace.step.review": { vi: "Tạo & xem", en: "Create & Review" },
  "workspace.step.deliver": { vi: "Bàn giao", en: "Deliver" },
  "workspace.heading.setup": { vi: "Thiết lập dự án", en: "Project setup" },
  "workspace.heading.media": { vi: "Thêm ảnh và nhạc", en: "Add photos and music" },
  "workspace.heading.direct": { vi: "Đạo diễn và chỉnh sửa", en: "Direct and edit" },
  "workspace.heading.review": { vi: "Tạo và xem lại", en: "Create and review" },
  "workspace.heading.deliver": { vi: "Duyệt và bàn giao", en: "Approve and deliver" },
  "workspace.continueTo": { vi: "Tiếp tục tới {step}", en: "Continue to {step}" },
  "workspace.fixPrerequisite": { vi: "Xử lý điều kiện còn thiếu", en: "Fix prerequisite" },
  "workspace.renderBlocked": { vi: "Bạn vẫn dựng được phim này, nhưng chưa tạo được video.", en: "You can build this film, but not create the video yet." },
  "workspace.viewPlans": { vi: "Xem các gói", en: "View plans" },

  "setup.description": { vi: "Xem lại thoả thuận sáng tạo trước khi thêm ảnh và nhạc.", en: "Review the creative contract before adding media." },
  "setup.fact.project": { vi: "Dự án", en: "Project" },
  "setup.fact.tier": { vi: "Gói", en: "Tier" },
  "setup.fact.style": { vi: "Phong cách", en: "Style" },
  "setup.fact.language": { vi: "Ngôn ngữ", en: "Language" },
  "setup.fact.photoOrder": { vi: "Thứ tự ảnh", en: "Photo order" },
  "setup.fact.quality": { vi: "Chất lượng đầu ra", en: "Output quality" },
  "setup.aiDirector": { vi: "AI Director", en: "AI Director" },
  "setup.ready": { vi: "Thiết lập đã sẵn sàng", en: "Setup is ready" },
  "setup.readyDetail": { vi: "Thêm ảnh gốc và nhạc nền cho phim này.", en: "Add the source photos and soundtrack for this film." },

  "media.description": { vi: "Tệp tự động tải lên sau khi chọn. Thứ tự tải lên được giữ nguyên cho bản dựng theo thời gian.", en: "Files upload automatically after selection. Upload order is preserved for chronological edits." },
  "media.uploading": { vi: "Đang tải lên…", en: "Uploading…" },
  "media.photosAdded_one": { vi: "Đã thêm {count} ảnh", en: "{count} photo added" },
  "media.photosAdded_other": { vi: "Đã thêm {count} ảnh", en: "{count} photos added" },
  "media.needPhoto": { vi: "Thêm ít nhất một ảnh", en: "Add at least one photo" },
  "media.tracksAdded_one": { vi: "Đã thêm {count} bản nhạc", en: "{count} soundtrack added" },
  "media.tracksAdded_other": { vi: "Đã thêm {count} bản nhạc", en: "{count} soundtracks added" },
  "media.needMusic": { vi: "Thêm một bản nhạc nền", en: "Add a soundtrack" },
  "media.photos": { vi: "Ảnh cưới", en: "Wedding photos" },
  "media.photosHint": { vi: "JPEG, PNG, WebP hoặc HEIC · tối đa 50 MB mỗi tệp", en: "JPEG, PNG, WebP or HEIC · up to 50 MB each" },
  "media.music": { vi: "Nhạc nền", en: "Soundtrack" },
  "media.musicHint": { vi: "MP3, WAV, M4A, AAC, FLAC hoặc OGG · tối đa 200 MB mỗi tệp", en: "MP3, WAV, M4A, AAC, FLAC or OGG · up to 200 MB each" },
  "media.dropPhotos": { vi: "Thả ảnh vào đây", en: "Drop photos here" },
  "media.dropMusic": { vi: "Thả nhạc vào đây", en: "Drop music here" },
  "media.autoUpload": { vi: "Tệp tự động tải lên sau khi chọn", en: "Files upload automatically after selection" },
  "media.chooseFiles": { vi: "Chọn tệp", en: "Choose files" },
  "media.deleteAsset": { vi: "Xoá {name}", en: "Delete {name}" },
  "media.retryUpload": { vi: "Tải lại {name}", en: "Retry {name}" },
  "media.removeFromQueue": { vi: "Bỏ {name} khỏi hàng đợi", en: "Remove {name}" },
  "media.queued": { vi: "đang chờ", en: "queued" },
  "media.uploadingStatus": { vi: "đang tải lên", en: "uploading" },
  "media.errorStatus": { vi: "lỗi", en: "error" },
  "media.unsupportedPhoto": { vi: "Định dạng ảnh không được hỗ trợ", en: "Unsupported photo file type" },
  "media.unsupportedMusic": { vi: "Định dạng nhạc không được hỗ trợ", en: "Unsupported music file type" },
  "media.tooLarge": { vi: "Tệp vượt quá {limit}", en: "File exceeds {limit}" },
  "media.empty": { vi: "Tệp rỗng", en: "File is empty" },
  "media.ready": { vi: "Ảnh và nhạc đã sẵn sàng", en: "Media is ready" },
  "media.readyDetail": { vi: "Tiếp tục để đạo diễn câu chuyện và xem bản dựng.", en: "Continue to direct the story and inspect the edit." },
  "media.incomplete": { vi: "Hoàn thành danh sách ảnh và nhạc", en: "Complete the media checklist" },
  "media.incompleteDetail": { vi: "Một phim cần có ảnh và ít nhất một bản nhạc nền trước khi tạo được.", en: "A film needs photos and at least one soundtrack before it can be created." },
  "media.previewUnavailable": { vi: "Không xem trước được", en: "Preview unavailable" },

  "direct.templateDescription": { vi: "Dự án này chạy theo phong cách đã chọn. Hãy tạo video ở bước sau, rồi quay lại đây để xem bản dựng.", en: "This project follows its selected style. Create the video in the next step, then come back here to inspect the edit." },
  "direct.aiDescription": { vi: "Định hình câu chuyện cùng AI Director, rồi xem từng cảnh và yêu cầu chỉnh sửa có trọng tâm.", en: "Shape the story with AI Director, then inspect scenes and request focused revisions." },
  "direct.ready": { vi: "Sẵn sàng tạo video", en: "Ready to create the video" },
  "direct.readyDetail": { vi: "Việc kết xuất và kiểm tra chất lượng sẽ chạy tự động.", en: "Rendering and quality checks will run automatically." },
  "style.setsDirection": { vi: "Phong cách quyết định hướng đi", en: "The style sets the direction" },
  "style.setsDirectionDetail": { vi: "{name} quyết định diện mạo, nhịp phim và hiệu ứng chuyển cảnh, nên ở đây không có gì cần chỉnh tay.", en: "{name} decides the look, pacing and transitions of this film, so there is nothing to direct by hand here." },
  "style.selectedStyle": { vi: "Phong cách đã chọn", en: "The selected style" },
  "style.scenesAndLooks": { vi: "{scenes} cảnh · {looks} tạo hình", en: "{scenes} scenes · {looks} looks" },
  "style.energy": { vi: "tiết tấu {energy}", en: "{energy} energy" },
  "style.howToldTitle": { vi: "Phim được kể như thế nào", en: "How the film is told" },
  "style.worksBestWith": { vi: "Hợp nhất với:", en: "Works best with:" },
  "style.noHandDirection": { vi: "Phong cách này quyết định diện mạo, nhịp phim và chuyển cảnh, nên không có gì cần chỉnh tay. Bản dựng từng cảnh sẽ hiện bên dưới sau khi video được tạo.", en: "This style controls the look, pacing and transitions, so there is nothing to direct by hand. The scene-by-scene edit appears below once the video has been created." },

  "review.description": { vi: "Tạo video, theo dõi tiến độ, rồi xem kết quả và bản báo cáo chất lượng.", en: "Create the video, follow its progress, then watch the result and check the quality report." },
  "review.blocked": { vi: "Hãy thêm ảnh và nhạc nền ở bước Ảnh & nhạc trước khi tạo video.", en: "Add photos and a soundtrack in Media before creating the video." },
  "review.qualityReport": { vi: "Báo cáo chất lượng", en: "Quality report" },
  "review.qualityReportHint": { vi: "Các bước kiểm tra, sửa tự động và những gì cần người xem lại", en: "Checks, automatic repairs, and anything needing a human look" },
  "review.manualComplete": { vi: "Dự án đã được đánh dấu hoàn tất thủ công", en: "Project completed manually" },
  "review.manualCompleteDetail": { vi: "Bản video đã kết xuất được chấp nhận, nên dự án không cần qua cổng bàn giao tự động.", en: "The rendered video was accepted and the project no longer requires the automated delivery gate." },
  "review.deliveryReady": { vi: "Gói bàn giao đã sẵn sàng", en: "Delivery package is ready" },
  "review.deliveryReadyDetail": { vi: "Tiếp tục để duyệt đúng bản xem trước này và phát hành bản master.", en: "Continue to approve the exact preview and release the master." },
  "review.passedQa": { vi: "Video đã qua kiểm tra chất lượng", en: "Your video passed quality checks" },
  "review.passedQaDetail": { vi: "Xem lại video rồi tiếp tục sang bước duyệt và bàn giao.", en: "Review the video, then continue to approval and delivery." },
  "review.qaRunning": { vi: "Đã kết xuất video; đang kiểm tra chất lượng ({progress}%)", en: "Video rendered; quality checks are running ({progress}%)" },
  "review.qaRunningDetail": { vi: "Phim đã được kết xuất. Việc kiểm tra chất lượng chạy tự động và trang này tự cập nhật.", en: "The film is rendered. Quality checks run automatically and this page updates live." },
  "review.createFirst": { vi: "Hãy tạo video trước", en: "Create a video first" },
  "review.createFirstDetail": { vi: "Video và báo cáo chất lượng được tạo tự động.", en: "The video and quality report are produced automatically." },

  "deliver.description": { vi: "Xem bản xem trước hiện tại, duyệt đúng phiên bản đó, rồi phát hành tệp cuối cùng.", en: "Review the current preview, approve its exact version, then release the final files." },
  "deliver.manualCompleteDetail": { vi: "Bản video đã kết xuất được chấp nhận ở bước {step}. Dự án này không cần duyệt bàn giao tự động.", en: "The rendered video was accepted in {step}. Automated delivery approval is not required for this project." },
  "deliver.needPreview": { vi: "Dùng “Tạo video” ở bước {step} để tạo bản xem trước và bản master đầy đủ.", en: "Use “Create video” in {step} to produce the preview and full master." },

  // ── Job runner ──────────────────────────────────────────────────────────
  "job.title": { vi: "Tạo phim của bạn", en: "Create your film" },
  "job.description": { vi: "Chúng tôi chuẩn bị câu chuyện, kết xuất video và kiểm tra chất lượng một cách tự động.", en: "We prepare the story, render the video, and check its quality automatically." },
  "job.live": { vi: "Trực tiếp", en: "Live" },
  "job.reconnecting": { vi: "Đang kết nối lại", en: "Reconnecting" },
  "job.creditNeeded": { vi: "Cần một lượt kết xuất", en: "A render credit is needed" },
  "job.runsOnItsOwn": { vi: "Mọi thứ bên dưới sẽ tự chạy sau khi bạn bắt đầu — bạn có thể để trang này mở, hoặc quay lại sau.", en: "Everything below runs on its own once you start — you can leave this page open, or come back to it later." },
  "job.stopping": { vi: "Đang dừng…", en: "Stopping…" },
  "job.starting": { vi: "Đang bắt đầu…", en: "Starting…" },
  "job.tryAgain": { vi: "Thử lại", en: "Try again" },
  "job.createVideo": { vi: "Tạo video", en: "Create video" },
  "job.finishedWithWarning": { vi: "Video hoàn tất kèm cảnh báo.", en: "The video finished with a warning." },
  "job.manualCompleteDetail": { vi: "Dự án này được đánh dấu hoàn tất thủ công; không có gói bàn giao tự động (xem trước, ảnh đại diện, bản master) nào được tạo.", en: "This project was marked complete manually; no automated delivery package (preview, thumbnail, master) was produced." },
  "job.filmReady": { vi: "Phim của bạn đã sẵn sàng để xem lại", en: "Your film is ready to review" },
  "job.needsAttention": { vi: "Pipeline cần được xử lý", en: "The pipeline needs attention" },
  "job.paused": { vi: "Pipeline đang tạm dừng", en: "The pipeline is paused" },
  "job.startingPipeline": { vi: "Đang khởi động pipeline", en: "Starting the pipeline" },
  "job.readyToStart": { vi: "Sẵn sàng bắt đầu", en: "Ready to start" },
  "job.detailRunning": { vi: "Tiến độ tự cập nhật. Bạn có thể để trang này mở trong lúc phim được chuẩn bị.", en: "Progress updates automatically. You can keep this page open while the film is being prepared." },
  "job.detailCompleted": { vi: "Đã xử lý xong. Phim mới nhất có ở phần Xem kết quả bên dưới.", en: "Processing is complete. The latest film is available in Render review below." },
  "job.detailFailed": { vi: "Xem lỗi và nhật ký trực tiếp, rồi chạy lại pipeline.", en: "Check the error and live output, then run the pipeline again." },
  "job.detailPaused": { vi: "Chạy lại để tiếp tục tự động từ phần đã hoàn thành gần nhất.", en: "Run again to continue automatically from the latest completed work." },
  "job.detailIdle": { vi: "Tạo phim; việc kết xuất và kiểm tra chất lượng sẽ chạy tự động.", en: "Create the film; rendering and quality checks run automatically." },
  "job.complete": { vi: "hoàn thành", en: "complete" },
  "job.technicalDetails": { vi: "Chi tiết kỹ thuật", en: "Technical details" },
  "job.livePipelineOutput": { vi: "· nhật ký pipeline trực tiếp", en: "· live pipeline output" },
  "job.logLines_one": { vi: "{count} dòng", en: "{count} line" },
  "job.logLines_other": { vi: "{count} dòng", en: "{count} lines" },
  "job.logEmpty": { vi: "Nhật ký pipeline sẽ hiện ở đây sau khi công việc bắt đầu.", en: "Pipeline output will appear here after the job starts." },
  "job.phaseSkipped": { vi: "{label}: không cần cho dự án này", en: "{label}: not needed for this project" },
  "job.playlistMismatch": { vi: "Số lượng ảnh và thời lượng nhạc chưa khớp nhau.", en: "Photo count and playlist duration don’t line up." },
  "job.playlistMismatchDetail": { vi: "Danh sách nhạc dài {duration} giây cho {photos} ảnh — khoảng {perPhoto}s mỗi ảnh.", en: "The playlist runs {duration} seconds for {photos} photos — about {perPhoto}s per photo." },
  "job.playlistTooLong": { vi: "Video có thể bị chậm, mỗi ảnh giữ quá lâu.", en: "The video may feel slow, holding each photo too long." },
  "job.playlistTooShort": { vi: "Video có thể bị gấp, hoặc không dùng hết ảnh.", en: "The video may feel rushed, or not use every photo." },
  "job.continueAnyway": { vi: "Vẫn tiếp tục kết xuất", en: "Continue rendering anyway" },
  "job.continuing": { vi: "Đang tiếp tục…", en: "Continuing…" },

  // ── Render review (TemplateMvpPanel) ────────────────────────────────────
  "render.title": { vi: "Xem kết quả", en: "Watch the result" },
  "render.description": { vi: "Phát bản phim mới nhất và kiểm tra những tệp sản xuất đã sẵn sàng.", en: "Play the latest version of the film and check which production files are ready." },
  "render.refreshLabel": { vi: "Làm mới phần xem kết quả", en: "Refresh render review" },
  "render.productionFiles": { vi: "Tệp sản xuất", en: "Production files" },
  "render.needsReRender": { vi: "Cần kết xuất lại", en: "Needs re-render" },
  "render.staleHint": { vi: "Tệp này thuộc một phiên bản dựng cũ hơn. Hãy tạo lại video để cập nhật.", en: "This file is from an earlier version of the edit. Create the video again to bring it up to date." },
  "render.notProducedYet": { vi: "Chưa được tạo.", en: "Not produced yet." },
  "render.style": { vi: "Phong cách:", en: "Style:" },
  "render.downloadFilm": { vi: "Tải phim về", en: "Download film" },
  "render.summary": { vi: "Bản tóm tắt", en: "Summary" },
  "render.loadingFilm": { vi: "Đang tải phim đã kết xuất…", en: "Loading rendered film…" },
  "render.playerAfterRender": { vi: "Trình phát sẽ xuất hiện sau khi kết xuất xong.", en: "The review player appears after a render completes." },
  "render.showingPreview": { vi: "Đang hiển thị bản xem trước bàn giao.", en: "Showing the delivery preview." },
  "render.showingLatest": { vi: "Đang hiển thị phim kết xuất mới nhất.", en: "Showing the latest rendered film." },

  // ── Artifacts ───────────────────────────────────────────────────────────
  "artifact.timeline": { vi: "Bản dựng", en: "Edit plan" },
  "artifact.render": { vi: "Phim đã kết xuất", en: "Rendered film" },
  "artifact.qa-report": { vi: "Báo cáo chất lượng", en: "Quality report" },
  "artifact.preview": { vi: "Bản xem trước", en: "Preview" },
  "artifact.delivery": { vi: "Bản master bàn giao", en: "Delivery master" },
  "artifact.thumbnail": { vi: "Ảnh đại diện", en: "Thumbnail" },
  "artifact.summary": { vi: "Tóm tắt dự án", en: "Project summary" },

  // ── Timeline viewer ─────────────────────────────────────────────────────
  "timeline.title": { vi: "Từng cảnh một", en: "Scene by scene" },
  "timeline.description": { vi: "Xem mạch phim và thay một ảnh đơn lẻ mà không phải dựng lại câu chuyện.", en: "Inspect how the film flows and swap a single photo without rebuilding the story." },
  "timeline.sceneSummary": { vi: "{count} cảnh · {duration}", en: "{count} scenes · {duration}" },
  "timeline.chooseReplacement": { vi: "Hãy chọn ảnh thay thế trước.", en: "Choose a replacement photo first." },
  "timeline.replaced": { vi: "Đã thay ảnh. Bản kết xuất, kiểm tra chất lượng, xem trước và bàn giao giờ đã cũ; hãy chạy lại pipeline.", en: "Image replaced. Render, QA, preview, and delivery are now stale; run the pipeline again." },
  "timeline.notReady": { vi: "Chưa có bản dựng nào để xem", en: "There is no edit to inspect yet" },
  "timeline.notReadyDetail": { vi: "Dùng “Tạo video” ở bước {step}. Bản dựng từng cảnh sẽ hiện ở đây sau khi được tạo.", en: "Use “Create video” in the {step} step. The scene-by-scene edit appears here once it has been built." },
  "timeline.storyFlow": { vi: "Mạch câu chuyện", en: "Story flow" },
  "timeline.clickScene": { vi: "Bấm vào một cảnh để xem chi tiết", en: "Click a scene to inspect it" },
  "timeline.meta.effect": { vi: "Hiệu ứng", en: "Effect" },
  "timeline.meta.layout": { vi: "Bố cục / bộ dựng", en: "Layout / renderer" },
  "timeline.meta.transition": { vi: "Chuyển cảnh", en: "Transition" },
  "timeline.caption": { vi: "Phụ đề", en: "Caption" },
  "timeline.assignedImages": { vi: "Ảnh đã gán", en: "Assigned images" },
  "timeline.slots_one": { vi: "{count} vị trí", en: "{count} slot" },
  "timeline.slots_other": { vi: "{count} vị trí", en: "{count} slots" },
  "timeline.chooseUploaded": { vi: "Chọn ảnh đã tải lên…", en: "Choose uploaded photo…" },
  "timeline.replace": { vi: "Thay ảnh", en: "Replace" },
  "timeline.noSlots": { vi: "Cảnh này không có vị trí ảnh nào để thay.", en: "This scene has no replaceable image slot." },
  "timeline.scenePreview": { vi: "Xem trước cảnh {index}", en: "Scene {index} preview" },
  "timeline.sceneAlt": { vi: "Cảnh {index}", en: "Scene {index}" },
  "timeline.loadingPreview": { vi: "Đang tải bản xem trước…", en: "Loading preview…" },
  "timeline.noPreview": { vi: "Chưa có bản kết xuất mới hoặc ảnh xem trước", en: "No fresh render or image preview" },
  "timeline.previewHint": { vi: "Bắt đầu trước khi cảnh kết thúc 2,5 giây để kiểm tra hiệu ứng ở khung hình cuối.", en: "Starts 2.5 seconds before the scene ends so reveal effects can be checked at their final frame." },
  "slot.image": { vi: "Ảnh chính", en: "Hero image" },
  "slot.images": { vi: "Ảnh {index}", en: "Image {index}" },
  "slot.layer": { vi: "Lớp {index}", en: "Layer {index}" },
  "slot.asset": { vi: "Tệp {index}", en: "Asset {index}" },

  // ── Revision panel ──────────────────────────────────────────────────────
  "revision.title": { vi: "Yêu cầu AI director chỉnh sửa", en: "Ask the AI director for a revision" },
  "revision.description": { vi: "Mô tả thay đổi bằng lời thường. Bản xem trước cho thấy phạm vi ảnh hưởng trước khi có gì bị đổi.", en: "Describe the change in plain language. Preview shows its reach before anything is changed." },
  "revision.roundsLeft": { vi: "Còn {remaining}/{max} lượt", en: "{remaining} of {max} rounds left" },
  "revision.placeholder": { vi: "Ví dụ: Bỏ phụ đề ở cảnh 12, làm chậm đoạn gia đình, và dùng chuyển cảnh lật trang…", en: "E.g. Remove the caption in scene 12, slow down the family chapter, and use a film-page transition…" },
  "revision.preview": { vi: "Xem trước thay đổi", en: "Preview changes" },
  "revision.previewing": { vi: "Đang xem trước…", en: "Previewing…" },
  "revision.apply": { vi: "Áp dụng chỉnh sửa", en: "Apply revision" },
  "revision.applied": { vi: "Đã áp dụng lượt {round}. Các giai đoạn pipeline liên quan và bản xem trước cũ giờ đã lỗi thời.", en: "Round {round} applied. The affected pipeline phases and old delivery preview are now stale." },
  "revision.undone": { vi: "Đã rút lại lượt {round}. Hãy chạy lại pipeline để tạo bản đã khôi phục.", en: "Round {round} withdrawn. Re-run the pipeline to produce the restored cut." },
  "revision.proposedRound": { vi: "Đề xuất lượt {round}", en: "Proposed round {round}" },
  "revision.destructive": { vi: "Có cảnh hoặc chữ bị xoá", en: "Scenes or text removed" },
  "revision.restoryWarning": { vi: "Đây là một cách kể lại: các hồi, lời thoại và ảnh đều có thể thay đổi. Engine không thể hứa trước một bản so sánh cảnh chính xác trước khi dựng lại.", en: "This is a re-telling: acts, words, and photos may all change. The engine cannot promise an exact scene diff before rebuilding." },
  "revision.destructiveWarning": { vi: "Thay đổi này xoá các cảnh hoặc đúng đoạn chữ được liệt kê bên dưới.", en: "This change removes the scenes or exact text listed below." },
  "revision.restoryConfirm": { vi: "Tôi hiểu việc này tạo ra một cách kể mới cho phim, không phải một chỉnh sửa nhỏ.", en: "I understand this creates a new telling of the film, not a narrow edit." },
  "revision.history": { vi: "Lịch sử chỉnh sửa", en: "Revision history" },
  "revision.round": { vi: "Lượt {round}", en: "Round {round}" },
  "revision.undoQuestion": { vi: "Hoàn tác lượt này?", en: "Undo this round?" },
  "revision.undo": { vi: "Hoàn tác", en: "Undo" },
  "revision.radius.timeline": { vi: "Chỉ timeline", en: "Timeline only" },
  "revision.radius.build": { vi: "Dựng lại từ câu chuyện", en: "Rebuild from story" },
  "revision.radius.restory": { vi: "Kể lại cả phim", en: "Re-story film" },

  // ── AI Director panel ───────────────────────────────────────────────────
  "director.title": { vi: "AI Director · {tier}", en: "AI Director · {tier}" },
  "director.description": { vi: "Biến định hướng của bạn thành một câu chuyện có thể kiểm chứng trước khi tạo timeline.", en: "Turn your direction into an auditable story before generating the timeline." },
  "director.instructions": { vi: "Chỉ dẫn cho đạo diễn", en: "Director instructions" },
  "director.placeholder": { vi: "Cho AI biết vai trò, dàn ý câu chuyện, cảm xúc, khoảnh khắc quan trọng, nhịp phim, ghi chú về nhạc, ràng buộc và mọi điều cần tuân theo…", en: "Give the AI a role, story outline, mood, important moments, pacing, music notes, constraints, and anything else it should follow…" },
  "director.premiumHint": { vi: "Tạo bốn hướng khác biệt A–D.", en: "Creates four distinct directions A–D." },
  "director.liteHint": { vi: "Lite tạo một câu chuyện súc tích từ bản brief.", en: "Lite creates one concise story from the brief." },
  "director.generate": { vi: "Tạo câu chuyện", en: "Generate story" },
  "director.regenerate": { vi: "Tạo lại câu chuyện", en: "Regenerate story" },
  "director.generating": { vi: "Đang tạo…", en: "Generating…" },
  "director.premiumGenerated": { vi: "Đã tạo bốn hướng. Dự án đang chờ bạn chọn câu chuyện.", en: "Four directions generated. The project is waiting for a story choice." },
  "director.liteGenerated": { vi: "Đã tạo câu chuyện. Tiếp tục để tạo video.", en: "Story generated. Continue to create the video." },
  "director.generatedStory": { vi: "Câu chuyện đã tạo", en: "Generated story" },
  "director.generated": { vi: "đã tạo", en: "generated" },
  "director.storyDirections": { vi: "Các hướng câu chuyện", en: "Story directions" },
  "director.storyDirectionsHint": { vi: "Chọn một hướng để tạo ghi chú đạo diễn và kế hoạch năm hồi.", en: "Choose one direction to generate director notes and the five-act plan." },
  "director.waiting": { vi: "Đang chờ · {remaining} · đến {deadline}", en: "Waiting · {remaining} · until {deadline}" },
  "director.hoursLeft": { vi: "còn {hours}g {minutes}p", en: "{hours}h {minutes}m left" },
  "director.minutesLeft": { vi: "còn {minutes}p", en: "{minutes}m left" },
  "director.directionSelected": { vi: "Đã chọn hướng {id}. Ghi chú đạo diễn và kế hoạch năm hồi đã sẵn sàng.", en: "Direction {id} selected. Director notes and five-act plan are ready." },
  "director.mood": { vi: "Cảm xúc:", en: "Mood:" },
  "director.whyItFits": { vi: "Vì sao phù hợp:", en: "Why it fits:" },
  "director.musicWindow": { vi: "Khung nhạc", en: "Music window" },
  "director.musicWindowHint": { vi: "Chọn đoạn cao trào ngắn hơn hoặc giữ nguyên cả bài.", en: "Choose the shorter emotional highlight or keep the complete track." },
  "director.suggestedHighlight": { vi: "Đoạn cao trào đề xuất: {start}–{end} ({duration}s)", en: "Suggested highlight: {start}–{end} ({duration}s)" },
  "director.useHighlight": { vi: "Dùng đoạn cao trào", en: "Use highlight" },
  "director.keepFullSong": { vi: "Giữ trọn bài", en: "Keep full song" },
  "director.highlightSelected": { vi: "Đã chọn khung nhạc cao trào.", en: "Highlight music window selected." },
  "director.fullSongSelected": { vi: "Đã chọn trọn bài.", en: "Full song selected." },
  "director.decisions": { vi: "Những gì AI đã quyết định", en: "What the AI decided" },
  "director.decisionsHint": { vi: "Các quyết định có kiểm soát được ghi lại để đối chiếu, không chỉ là lời văn.", en: "Guardrailed decisions recorded for audit, not just prose." },
  "director.fiveActPlan": { vi: "Kế hoạch năm hồi", en: "Five-act story plan" },
  "director.fiveActFlow": { vi: "Mở đầu → Chuyện tình → Lễ cưới → Gia đình & bạn bè → Kết", en: "Opening → Love Story → Ceremony → Family & Friends → Ending" },
  "director.readyForTimeline": { vi: "Sẵn sàng dựng timeline", en: "Ready for timeline" },
  "director.effect": { vi: "Hiệu ứng: {effect}", en: "Effect: {effect}" },
  "director.continueHint": { vi: "Tiếp tục sang bước {step} — phim được dựng từ kế hoạch này.", en: "Continue to {step} — the film is built from this plan." },

  // ── Analysis panel ──────────────────────────────────────────────────────
  "analysis.title": { vi: "Phân tích ảnh & nhạc", en: "Photos & Music Analysis" },
  "analysis.description": { vi: "Các phép đo kỹ thuật chạy tại chỗ. Phân tích thị giác là tuỳ chọn, có tính phí và cần xác nhận.", en: "Technical measurements are local. Vision is optional, priced, and requires confirmation." },
  "analysis.technical": { vi: "Phân tích kỹ thuật", en: "Technical analysis" },
  "analysis.technicalHint": { vi: "Lượt quét FFmpeg/FFprobe tại chỗ để đo kích thước, độ nét, độ sáng, khuôn mặt, ảnh trùng và nhịp nhạc.", en: "Local FFmpeg/FFprobe pass for dimensions, sharpness, exposure, faces, duplicates, and music rhythm." },
  "analysis.uploaded": { vi: "Đã tải lên", en: "Uploaded" },
  "analysis.analyzed": { vi: "Đã phân tích", en: "Analyzed" },
  "analysis.tracks": { vi: "Bản nhạc", en: "Tracks" },
  "analysis.runTechnical": { vi: "Phân tích ảnh & nhạc", en: "Analyze photos & music" },
  "analysis.rerunTechnical": { vi: "Chạy lại phân tích kỹ thuật", en: "Re-run technical analysis" },
  "analysis.vision": { vi: "Phân tích thị giác", en: "Vision analysis" },
  "analysis.visionHint": { vi: "Gắn thẻ ngữ nghĩa, cảm xúc và mức quan trọng trong câu chuyện bằng {model}.", en: "Semantic tags, emotion and story importance using {model}." },
  "analysis.configuredModel": { vi: "mô hình đã cấu hình", en: "the configured model" },
  "analysis.photos": { vi: "Ảnh", en: "Photos" },
  "analysis.requests": { vi: "Lượt gọi", en: "Requests" },
  "analysis.estimatedUsd": { vi: "Ước tính USD", en: "Est. USD" },
  "analysis.visionConsent": { vi: "Tôi đã xem ước tính này và đồng ý gửi {count} ảnh xem trước tới {provider}.", en: "I reviewed this estimate and approve sending {count} photo previews to {provider}." },
  "analysis.provider": { vi: "nhà cung cấp", en: "the provider" },
  "analysis.runVision": { vi: "Chạy phân tích thị giác", en: "Run vision analysis" },
  "analysis.rerunVision": { vi: "Chạy lại phân tích thị giác", en: "Re-run vision" },
  "analysis.starting": { vi: "Đang bắt đầu…", en: "Starting…" },
  "analysis.visionNotConfigured": { vi: "Hãy cấu hình nhà cung cấp có thị giác và API key trước khi chạy bước tính phí này.", en: "Configure a vision-capable provider and API key before running this paid step." },
  "analysis.music": { vi: "Phân tích nhạc", en: "Music analysis" },
  "analysis.waitingForTechnical": { vi: "Đang chờ phân tích kỹ thuật", en: "Waiting for technical analysis" },
  "analysis.cull": { vi: "Trợ lý lọc ảnh", en: "Cull advisor" },
  "analysis.cullHint": { vi: "Tạo một đề xuất để bạn xem lại. Không ảnh gốc nào bị xoá, và lựa chọn chỉ đổi sau khi bấm Áp dụng.", en: "Generate a reviewable proposal. No source photo is deleted, and selection changes only after Apply." },
  "analysis.photosToKeep": { vi: "Số ảnh giữ lại", en: "Photos to keep" },
  "analysis.suggest": { vi: "Đề xuất", en: "Suggest" },
  "analysis.proposedRemovals": { vi: "Đề xuất loại bỏ theo lý do", en: "Proposed removals by reason" },
  "analysis.dropCount": { vi: "{drop} / {total}", en: "{drop} of {total}" },
  "analysis.groupPhotos_one": { vi: "{count} ảnh", en: "{count} photo" },
  "analysis.groupPhotos_other": { vi: "{count} ảnh", en: "{count} photos" },
  "analysis.quality": { vi: "Chất lượng {percent}%", en: "Quality {percent}%" },
  "analysis.nothingToRemove": { vi: "Không có gì cần loại bỏ.", en: "Nothing needs to be removed." },
  "analysis.keptCount": { vi: "Giữ lại {count}", en: "{count} kept" },
  "analysis.protectedCount": { vi: "Bảo vệ {count}", en: "{count} protected" },
  "analysis.applyHint": { vi: "Áp dụng chỉ cập nhật danh sách ảnh được chọn. Tệp gốc không bị đụng tới.", en: "Applying updates the selected-photo list only. Original files remain untouched." },
  "analysis.shortfall": { vi: "Thiếu {count}; các ảnh đã khoá vẫn được bảo vệ.", en: "Short by {count}; locked photos remain protected." },
  "analysis.cullConsent": { vi: "Tôi đã xem các nhóm đề xuất và muốn cập nhật lựa chọn.", en: "I reviewed the proposed groups and want to update the selection." },
  "analysis.applyCull": { vi: "Áp dụng lọc ảnh", en: "Apply cull" },
  "analysis.cullApplied": { vi: "Đã áp dụng: chọn {keep}/{total}", en: "Applied: {keep}/{total} selected" },
  "analysis.output": { vi: "Nhật ký phân tích", en: "Analysis output" },
  "analysis.probeErrors": { vi: "Lỗi khi đọc tệp", en: "Media probe errors" },
  "analysis.group.duplicates": { vi: "Ảnh trùng và gần trùng", en: "Duplicates and near-duplicates" },
  "analysis.group.blur": { vi: "Mờ hoặc chất lượng kỹ thuật thấp", en: "Blur or low technical quality" },
  "analysis.group.exposure": { vi: "Phơi sáng và ánh sáng", en: "Exposure and lighting" },
  "analysis.group.other": { vi: "Đề xuất khác", en: "Other recommendations" },

  // ── QA panel ────────────────────────────────────────────────────────────
  "qa.title": { vi: "Kiểm tra chất lượng", en: "Quality checks" },
  "qa.description": { vi: "Kiểm tra nhịp phim và bố cục trước khi kết xuất, soi các khung hình đã kết xuất, rồi áp dụng một số sửa lỗi tự động có giới hạn.", en: "Checks pacing and framing before rendering, inspects the rendered frames, then applies a limited number of automatic fixes." },
  "qa.refreshLabel": { vi: "Làm mới trạng thái kiểm tra chất lượng", en: "Refresh QA status" },
  "qa.loading": { vi: "Đang tải trạng thái kiểm tra chất lượng…", en: "Loading QA status…" },
  "qa.notReady": { vi: "Chưa có gì để báo cáo. Dùng “Tạo video” ở trên — bước kiểm tra chất lượng tự chạy và điền vào đây.", en: "Nothing to report yet. Use “Create video” above — the quality stage runs on its own and fills this in." },
  "qa.stage.preflight": { vi: "1. Tiền kiểm", en: "1. Pre-flight" },
  "qa.stage.render": { vi: "2. Kiểm tra bản kết xuất", en: "2. Render checks" },
  "qa.stage.revise": { vi: "3. Tự sửa", en: "3. Auto-revise" },
  "qa.passes_one": { vi: "{count} lượt", en: "{count} pass" },
  "qa.passes_other": { vi: "{count} lượt", en: "{count} passes" },
  "qa.freeRepairs_one": { vi: "{count} lần sửa miễn phí · không tốn lượt chỉnh sửa", en: "{count} free repair · no revision budget" },
  "qa.freeRepairs_other": { vi: "{count} lần sửa miễn phí · không tốn lượt chỉnh sửa", en: "{count} free repairs · no revision budget" },
  "qa.safetyCap": { vi: "Đã chạm giới hạn an toàn", en: "Safety cap reached" },
  "qa.frameIssues_one": { vi: "{count} lỗi khung hình", en: "{count} frame issue" },
  "qa.frameIssues_other": { vi: "{count} lỗi khung hình", en: "{count} frame issues" },
  "qa.frameIssuesDetail": { vi: "Độ sáng, khung hình trống, bản proxy và cảnh mở/kết", en: "Brightness, empty frames, proxy and bookends" },
  "qa.revisionsUsed": { vi: "Đã dùng {used}/{max}", en: "{used}/{max} used" },
  "qa.revisingNow": { vi: "Đang áp dụng một bản sửa xác định", en: "Currently applying a deterministic repair" },
  "qa.revisionCost": { vi: "Mỗi lượt sẽ kết xuất lại và tốn hạn mức", en: "Each pass re-renders and spends budget" },
  "qa.runningRevising": { vi: "Kiểm tra chất lượng đang tự sửa bản dựng", en: "QA is automatically repairing the cut" },
  "qa.runningPreflight": { vi: "Tiền kiểm đang xét nhịp phim và lựa chọn ảnh chính", en: "Pre-flight is checking pacing and hero choices" },
  "qa.runningRender": { vi: "Đang soi phim đã kết xuất", en: "QA is inspecting the rendered film" },
  "qa.runningWaiting": { vi: "Đang chờ tới lượt trong pipeline", en: "QA is waiting for its pipeline phase" },
  "qa.runningDetail": { vi: "Công việc đang chạy. Bảng này tự làm mới.", en: "The job is active. This panel refreshes automatically." },
  "qa.unknownVerdict": { vi: "Các kiểm tra máy móc đã qua; kết luận chủ quan về cảnh mở/kết chưa xác định.", en: "Mechanical checks passed; subjective bookend verdict is unknown." },
  "qa.visionUnavailable": { vi: "Không có chấm điểm thị giác.", en: "Vision scoring was unavailable." },
  "qa.unknownNotFailure": { vi: "Chưa xác định không phải là lỗi pipeline.", en: "Unknown is not a pipeline failure." },
  "qa.allPassed": { vi: "Tất cả các lớp kiểm tra đang bật đều đã qua.", en: "All enabled QA layers passed." },
  "qa.manuallyAccepted": { vi: "Dự án đã kết xuất được đánh dấu hoàn tất thủ công.", en: "The rendered project was marked complete manually." },
  "qa.gateStopped": { vi: "Cổng kiểm tra chất lượng đã dừng pipeline.", en: "QA gate stopped the pipeline." },
  "qa.canCompleteManually": { vi: "Video đã kết xuất và có thể được hoàn tất thủ công.", en: "The video is rendered and can be completed manually." },
  "qa.repairsExhausted": { vi: "Đã hết lượt sửa tự động; cần người xem lại bản dựng hiện tại.", en: "Automatic repairs are exhausted; a person must review the current cut." },
  "qa.confirmManual": { vi: "Xác nhận hoàn tất dự án thủ công", en: "Confirm project complete manually" },
  "qa.confirming": { vi: "Đang xác nhận…", en: "Confirming…" },
  "qa.findings": { vi: "Phát hiện", en: "Findings" },
  "qa.manualReview": { vi: "Cần người xem", en: "Manual review" },
  "qa.renderedFrame": { vi: "Khung hình đã kết xuất", en: "Rendered frame" },
  "qa.journal_one": { vi: "Nhật ký sửa · {count} thay đổi", en: "Repair journal · {count} change" },
  "qa.journal_other": { vi: "Nhật ký sửa · {count} thay đổi", en: "Repair journal · {count} changes" },
  "qa.runsAutomatically": { vi: "Các kiểm tra này chạy tự động như một phần của việc tạo video.", en: "These checks run automatically as part of creating the video." },
  "qa.autoRevising": { vi: "Đang tự sửa", en: "Auto-revising" },
  "qa.running": { vi: "Đang kiểm tra", en: "QA running" },
  "qa.waiting": { vi: "Đang chờ kiểm tra", en: "Waiting for QA" },
  "qa.failed": { vi: "Kiểm tra thất bại", en: "QA failed" },
  "qa.notRun": { vi: "Chưa chạy", en: "Not run" },
  "qaVerdict.ok": { vi: "Đạt", en: "OK" },
  "qaVerdict.review": { vi: "Cần xem lại", en: "Review" },
  "qaVerdict.unknown": { vi: "Chưa xác định", en: "Unknown" },

  // ── Delivery panel ──────────────────────────────────────────────────────
  "delivery.title": { vi: "Bàn giao & vận hành", en: "Delivery & Operations" },
  "delivery.description": { vi: "Xem bản xem trước có đóng dấu, duyệt đúng bản dựng này, rồi phát hành bản master đầy đủ theo cách thủ công.", en: "Review the watermarked preview, approve this exact cut, then release the full master manually." },
  "delivery.approvalInvalid": { vi: "Lần duyệt trước không còn hiệu lực.", en: "Previous approval is invalid." },
  "delivery.approvalInvalidDetail": { vi: "{reason}. Hãy tạo và xem một bản xem trước mới trước khi phát hành.", en: "{reason}. Generate and review a fresh preview before release." },
  "delivery.previewStale": { vi: "Bản xem trước đã cũ sau khi timeline thay đổi", en: "Preview is stale after timeline changes" },
  "delivery.previewMissing": { vi: "Hãy chạy kết xuất, kiểm tra chất lượng và bàn giao để tạo bản xem trước", en: "Run Render, QA & delivery to create a preview" },
  "delivery.watermark": { vi: "Dấu chìm: {value}", en: "Watermark: {value}" },
  "delivery.checklist": { vi: "Danh sách trước phát hành", en: "Release checklist" },
  "delivery.check.preview": { vi: "Đã tạo bản xem trước hiện tại", en: "Current preview generated" },
  "delivery.check.approved": { vi: "Đã duyệt đúng bản xem trước", en: "Exact preview approved" },
  "delivery.check.master": { vi: "Đã đóng gói bản master đầy đủ", en: "Full master packaged" },
  "delivery.check.released": { vi: "Người vận hành đã phát hành bản master", en: "Operator released master" },
  "delivery.approve": { vi: "Duyệt bản xem trước hiện tại", en: "Approve current preview" },
  "delivery.approving": { vi: "Đang duyệt…", en: "Approving…" },
  "delivery.release": { vi: "Phát hành phim đầy đủ", en: "Release full film" },
  "delivery.releasing": { vi: "Đang phát hành…", en: "Releasing…" },
  "delivery.downloadReleased": { vi: "Tải phim đã phát hành", en: "Download released film" },
  "delivery.approvedAt": { vi: "Đã duyệt {date}", en: "Approved {date}" },
  "delivery.releasedAt": { vi: "Đã phát hành thủ công {date}. Điều này không hàm ý bất kỳ trạng thái thanh toán nào.", en: "Released manually {date}. No payment state is implied." },
  "delivery.sharing": { vi: "Chia sẻ công khai", en: "Public sharing" },
  "delivery.sharingLocked": { vi: "Hãy phát hành phim đầy đủ ở trên trước khi chia sẻ công khai.", en: "Release the full film above before it can be shared publicly." },
  "delivery.sharedState": { vi: "Đang hiển thị trong thư viện công khai", en: "Visible in the public gallery" },
  "delivery.privateState": { vi: "Riêng tư — chỉ bạn thấy dự án này", en: "Private — only you can see this project" },
  "delivery.copyLink": { vi: "Sao chép liên kết thư viện", en: "Copy gallery link" },
  "delivery.linkCopied": { vi: "Đã sao chép liên kết", en: "Link copied" },
  "delivery.makePrivate": { vi: "Chuyển về riêng tư", en: "Make private" },
  "delivery.sharePublicly": { vi: "Chia sẻ công khai", en: "Share publicly" },
  "delivery.updating": { vi: "Đang cập nhật…", en: "Updating…" },
  "delivery.deliverables": { vi: "Sản phẩm bàn giao", en: "Deliverables" },
  "delivery.auditedSummary": { vi: "Tóm tắt dự án đã đối chiếu", en: "Audited project summary" },
  "delivery.auditedSummaryHint": { vi: "Các giá trị được hiển thị đúng như đã ghi nhận; `unknown` không phải là phỏng đoán.", en: "Values are shown as recorded; `unknown` is not guessed." },
  "delivery.summaryTier": { vi: "Gói: {tier}", en: "Tier: {tier}" },
  "delivery.summary.photoAnalysis": { vi: "Phân tích ảnh", en: "Photo analysis" },
  "delivery.summary.qaVerdict": { vi: "Kết luận chất lượng", en: "QA verdict" },
  "delivery.summary.thumbnailChosenBy": { vi: "Ảnh đại diện do", en: "Thumbnail chosen by" },
  "delivery.summary.film": { vi: "Phim", en: "Film" },
  "delivery.summary.content": { vi: "{scenes} cảnh · {photos} ảnh khác nhau", en: "{scenes} scenes · {photos} unique photos" },

  // ── Billing ─────────────────────────────────────────────────────────────
  "billing.title": { vi: "Gói & thanh toán", en: "Plans & billing" },
  "billing.loading": { vi: "Đang tải các gói…", en: "Loading plans…" },
  "billing.loadFailed": { vi: "Không tải được thông tin thanh toán", en: "Unable to load billing" },
  "billing.perVideo": { vi: "Trả theo từng video", en: "Pay per video" },
  "billing.perVideoDetail": { vi: "— một phim hoàn chỉnh, không thu định kỳ.", en: "— one finished film, no recurring charge." },
  "billing.payByCard": { vi: "Thanh toán bằng thẻ", en: "Pay by card" },
  "billing.redirecting": { vi: "Đang chuyển hướng…", en: "Redirecting…" },
  "billing.openingMomo": { vi: "Đang mở MoMo…", en: "Opening MoMo…" },
  "billing.payWithMomo": { vi: "Thanh toán {amount} bằng MoMo", en: "Pay {amount} with MoMo" },
  "billing.subscription": { vi: "Gói thuê bao tháng", en: "Monthly subscription" },
  "billing.subscriptionDetail": { vi: "{price}/tháng — tối đa {quota} lượt kết xuất, thu theo tháng.", en: "{price}/month — up to {quota} renders, billed monthly." },
  "billing.rendersPerPeriod": { vi: "{quota} lượt kết xuất mỗi kỳ thanh toán", en: "{quota} renders every billing period" },
  "billing.cancelAnyTime": { vi: "Huỷ bất cứ lúc nào", en: "Cancel any time" },
  "billing.subscribe": { vi: "Đăng ký bằng thẻ", en: "Subscribe with card" },

  // ── Plan summary ────────────────────────────────────────────────────────
  "plan.creditsLeft_one": { vi: "Còn {count} lượt kết xuất", en: "{count} render credit left" },
  "plan.creditsLeft_other": { vi: "Còn {count} lượt kết xuất", en: "{count} render credits left" },
  "plan.quotaUsed": { vi: "Đã dùng {used}/{quota} lượt kết xuất trong kỳ này", en: "{used} of {quota} renders used this period" },
  "plan.noCredits": { vi: "Tài khoản này đã hết lượt kết xuất. Mỗi phim hoàn chỉnh tốn một lượt.", en: "This account has no render credits left. Each finished film costs one credit." },
  "plan.quotaExhausted": { vi: "Bạn đã dùng hết lượt kết xuất trong kỳ thanh toán hiện tại. Hạn mức sẽ đặt lại khi sang kỳ mới.", en: "You have used every render in the current billing period. The quota resets when the period rolls over." },

  // ── Gallery ─────────────────────────────────────────────────────────────
  "gallery.backToSignIn": { vi: "Quay lại đăng nhập", en: "Back to sign in" },
  "gallery.title": { vi: "Phim được chia sẻ", en: "Shared films" },
  "gallery.eyebrow": { vi: "Phòng chiếu", en: "The screening room" },
  "gallery.heading": { vi: "Những câu chuyện đáng nhớ", en: "Stories worth remembering" },
  "gallery.intro": { vi: "Tuyển tập những phim được chính tác giả chia sẻ, để cùng nhau xem lại.", en: "A collection of films shared by their creators, made to be watched together." },
  "gallery.loadFailed": { vi: "Không tải được thư viện", en: "Unable to load the gallery" },
  "gallery.loading": { vi: "Đang tải phim được chia sẻ…", en: "Loading shared films…" },
  "gallery.empty": { vi: "Chưa có phim nào được chia sẻ công khai.", en: "No films have been shared publicly yet." },
  "gallery.play": { vi: "Phát {name}", en: "Play {name}" },
  "gallery.watchFilm": { vi: "Xem phim", en: "Watch film" },
  "gallery.sharedOn": { vi: "Chia sẻ {date}", en: "Shared {date}" },

  // ── Recipe library ──────────────────────────────────────────────────────
  "recipes.eyebrow": { vi: "Gói mẫu có sẵn", en: "Tier template" },
  "recipes.title": { vi: "Thư viện phong cách", en: "Recipe Library" },
  "recipes.count": { vi: "{count} phong cách", en: "{count} recipes" },
  "recipes.search": { vi: "Tìm theo tên, phong cách hoặc cảm xúc…", en: "Search name, style, or mood…" },
  "recipes.filterByMood": { vi: "Lọc theo cảm xúc", en: "Filter by mood" },
  "recipes.allMoods": { vi: "Mọi cảm xúc", en: "All moods" },
  "recipes.photoCountFilter": { vi: "Chỉ hiện phong cách hợp với số ảnh này", en: "Show only styles that suit this many photos" },
  "recipes.photoCountPlaceholder": { vi: "Bao nhiêu ảnh?", en: "How many photos?" },
  "recipes.loading": { vi: "Đang tải thư viện phong cách…", en: "Loading recipe library…" },
  "recipes.showing": { vi: "Đang hiện {shown} trong {total} phong cách", en: "Showing {shown} of {total} recipes" },
  "recipes.noMatches": { vi: "Không có phong cách nào khớp bộ lọc.", en: "No recipe matches these filters." },
  "recipes.detailEyebrow": { vi: "Chi tiết phong cách", en: "Recipe details" },
  "recipes.scenes": { vi: "Cảnh", en: "Scenes" },
  "recipes.looks": { vi: "Tạo hình", en: "Looks" },
  "recipes.looksValue": { vi: "{signatures} trên {layouts}", en: "{signatures} on {layouts}" },
  "recipes.energy": { vi: "Tiết tấu", en: "Energy" },
  "recipes.flexible": { vi: "Linh hoạt", en: "Flexible" },
  "recipes.bestFit": { vi: "Hợp nhất với", en: "Best fit" },
  "recipes.photosLabel": { vi: "Ảnh: ", en: "Photos: " },
  "recipes.storyLabel": { vi: "Câu chuyện: ", en: "Story: " },
  "recipes.musicLabel": { vi: "Nhạc: ", en: "Music: " },
  "recipes.photoFit": { vi: "Số ảnh phù hợp", en: "Photo fit" },
  "recipes.photoFitDetail": { vi: "Tối thiểu {min} · Lý tưởng {ideal} · Tối đa {max}", en: "Minimum {min} · Ideal {ideal} · Maximum {max}" },
  "recipes.openMax": { vi: "không giới hạn", en: "open" },
  "recipes.storyArc": { vi: "Mạch câu chuyện", en: "Story arc" },
  "recipes.palette": { vi: "Bảng màu", en: "Palette" },
  "recipes.bestFor": { vi: "Phù hợp cho", en: "Best for" },
  "recipes.photoRange": { vi: "{min}–{ideal} ảnh", en: "{min}–{ideal} photos" },
  "recipes.photoRangeFrom": { vi: "Từ {min} ảnh", en: "From {min} photos" },
  "recipes.scenesAndLooks": { vi: "{scenes} cảnh · {looks} tạo hình", en: "{scenes} scenes · {looks} looks" },

  // ── Admin incidents ─────────────────────────────────────────────────────
  "admin.title": { vi: "Sự cố kỹ thuật", en: "Technical incidents" },
  "admin.needAttention_one": { vi: "{count} sự cố cần xử lý", en: "{count} incident needs attention" },
  "admin.needAttention_other": { vi: "{count} sự cố cần xử lý", en: "{count} incidents need attention" },
  "admin.occurrences_one": { vi: "xảy ra {count} lần", en: "occurred {count} time" },
  "admin.occurrences_other": { vi: "xảy ra {count} lần", en: "occurred {count} times" },
  "admin.phase": { vi: "giai đoạn {phase}", en: "phase {phase}" },
  "admin.customerImpact": { vi: "Ảnh hưởng tới khách hàng: {impact}", en: "Customer impact: {impact}" },
  "admin.technicalDetail": { vi: "Chi tiết kỹ thuật", en: "Technical detail" },
  "admin.investigate": { vi: "Điều tra", en: "Investigate" },
  "admin.retryStep": { vi: "Chạy lại bước lỗi", en: "Retry failed step" },
  "admin.markResolved": { vi: "Đánh dấu đã xử lý", en: "Mark resolved" },
  "admin.empty": { vi: "Không có sự cố kỹ thuật nào.", en: "No technical incidents." },
  "admin.status.new": { vi: "Mới", en: "New" },
  "admin.status.investigating": { vi: "Đang điều tra", en: "Investigating" },
  "admin.status.resolved": { vi: "Đã xử lý", en: "Resolved" },

  // ── API errors, keyed by the server's error code ────────────────────────
  // Anything not listed falls through to the server's own English message,
  // which is better than inventing a vague translated one.
  "apiError.NETWORK_ERROR": { vi: "Không kết nối được tới máy chủ. Hãy kiểm tra mạng rồi thử lại.", en: "Unable to reach the API. Check your connection and try again." },
  "apiError.REQUEST_FAILED": { vi: "Yêu cầu thất bại. Hãy thử lại.", en: "The request failed. Please try again." },
  "apiError.INVALID_RESPONSE": { vi: "Máy chủ trả về phản hồi không hợp lệ.", en: "The server returned an invalid response." },
  "apiError.INTERNAL_ERROR": { vi: "Máy chủ gặp lỗi không mong muốn.", en: "The server hit an unexpected error." },
  "apiError.UNAUTHENTICATED": { vi: "Phiên đăng nhập đã hết hạn. Hãy đăng nhập lại.", en: "Your session has expired. Please sign in again." },
  "apiError.ADMIN_REQUIRED": { vi: "Chỉ quản trị viên mới dùng được chức năng này.", en: "This action requires an admin account." },
  "apiError.INVALID_CREDENTIALS": { vi: "Sai tên đăng nhập hoặc mật khẩu.", en: "Incorrect username or password." },
  "apiError.INVALID_CURRENT_PASSWORD": { vi: "Mật khẩu hiện tại không đúng.", en: "The current password is incorrect." },
  "apiError.INVALID_USERNAME": { vi: "Tên đăng nhập chỉ gồm chữ thường, số và dấu gạch ngang.", en: "A username may only contain lowercase letters, numbers, and hyphens." },
  "apiError.USER_EXISTS": { vi: "Tên đăng nhập này đã có người dùng.", en: "That username is already taken." },
  "apiError.USER_NOT_FOUND": { vi: "Không tìm thấy tài khoản.", en: "Account not found." },
  "apiError.WEAK_PASSWORD": { vi: "Mật khẩu phải có ít nhất 8 ký tự.", en: "The password must be at least 8 characters." },
  "apiError.TOO_MANY_ATTEMPTS": { vi: "Quá nhiều lần thử. Hãy đợi một lát rồi thử lại.", en: "Too many attempts. Wait a moment and try again." },
  "apiError.ASSET_TOO_LARGE": { vi: "Tệp vượt quá dung lượng cho phép.", en: "The file is larger than the allowed limit." },
  "apiError.EMPTY_ASSET": { vi: "Tệp rỗng.", en: "The file is empty." },
  "apiError.UNSUPPORTED_ASSET_TYPE": { vi: "Định dạng tệp này không được hỗ trợ.", en: "That file type is not supported." },
  "apiError.INVALID_ASSET_KIND": { vi: "Loại tệp không hợp lệ.", en: "Invalid asset kind." },
  "apiError.ASSET_NOT_FOUND": { vi: "Không tìm thấy tệp.", en: "Asset not found." },
  "apiError.PROJECT_NOT_FOUND": { vi: "Không tìm thấy dự án.", en: "Project not found." },
  "apiError.PROJECT_EXISTS": { vi: "Đã có một dự án trùng tên.", en: "A project with that name already exists." },
  "apiError.PROJECT_BUSY": { vi: "Dự án đang bận. Hãy đợi công việc hiện tại kết thúc.", en: "The project is busy. Wait for the current job to finish." },
  "apiError.JOB_ALREADY_RUNNING": { vi: "Một công việc đang chạy cho dự án này.", en: "A job is already running for this project." },
  "apiError.JOB_NOT_RUNNING": { vi: "Không có công việc nào đang chạy.", en: "No job is currently running." },
  "apiError.RENDER_QUOTA_EXCEEDED": { vi: "Đã hết lượt kết xuất. Hãy xem lại gói của bạn.", en: "You are out of render credits. Check your plan." },
  "apiError.PREMIUM_REQUIRED": { vi: "Chức năng này chỉ có ở gói Premium.", en: "This feature requires the Premium tier." },
  "apiError.ARTIFACT_NOT_READY": { vi: "Tệp này chưa sẵn sàng.", en: "That file is not ready yet." },
  "apiError.ARTIFACT_NOT_FOUND": { vi: "Không tìm thấy tệp sản phẩm.", en: "Artifact not found." },
  "apiError.DELIVERY_NOT_READY": { vi: "Gói bàn giao chưa sẵn sàng.", en: "The delivery package is not ready." },
  "apiError.PREVIEW_NOT_READY": { vi: "Bản xem trước chưa sẵn sàng.", en: "The preview is not ready." },
  "apiError.PREVIEW_APPROVAL_REQUIRED": { vi: "Hãy duyệt bản xem trước trước khi phát hành.", en: "Approve the preview before releasing." },
  "apiError.PROJECT_NOT_RELEASED": { vi: "Hãy phát hành phim trước khi chia sẻ công khai.", en: "Release the film before sharing it publicly." },
  "apiError.TIMELINE_NOT_READY": { vi: "Chưa có timeline. Hãy tạo video trước.", en: "There is no timeline yet. Create the video first." },
  "apiError.MUSIC_REQUIRED": { vi: "Dự án này cần ít nhất một bản nhạc nền.", en: "This project needs at least one soundtrack." },
  "apiError.TECHNICAL_ANALYSIS_REQUIRED": { vi: "Hãy chạy phân tích kỹ thuật trước.", en: "Run the technical analysis first." },
  "apiError.VISION_NOT_CONFIGURED": { vi: "Chưa cấu hình nhà cung cấp thị giác.", en: "No vision provider is configured." },
  "apiError.ANALYSIS_ALREADY_RUNNING": { vi: "Một lượt phân tích đang chạy.", en: "An analysis is already running." },
  "apiError.REVISION_BUDGET_EXCEEDED": { vi: "Đã dùng hết số lượt chỉnh sửa.", en: "The revision budget is used up." },
  "apiError.RESTORY_CONFIRMATION_REQUIRED": { vi: "Thay đổi này cần bạn xác nhận kể lại cả phim.", en: "This change needs the re-story confirmation." },
  "apiError.STRIPE_NOT_CONFIGURED": { vi: "Chưa cấu hình thanh toán bằng thẻ.", en: "Card payment is not configured." },
  "apiError.MOMO_NOT_CONFIGURED": { vi: "Chưa cấu hình thanh toán MoMo.", en: "MoMo payment is not configured." },
  "apiError.MOMO_UNAVAILABLE": { vi: "Hiện chưa kết nối được MoMo. Hãy thử lại sau.", en: "MoMo is unavailable right now. Try again shortly." },
  "apiError.MOMO_CHECKOUT_FAILED": { vi: "Không tạo được thanh toán MoMo.", en: "Could not start the MoMo payment." },
  "apiError.CHECKOUT_SESSION_FAILED": { vi: "Không tạo được phiên thanh toán.", en: "Could not start the checkout session." },
  "apiError.ALREADY_SUBSCRIBED": { vi: "Tài khoản này đã có gói thuê bao.", en: "This account already has a subscription." },
  "apiError.RECIPE_NOT_FOUND": { vi: "Không tìm thấy phong cách.", en: "Recipe not found." },
  "apiError.VALIDATION_ERROR": { vi: "Có trường nhập chưa hợp lệ.", en: "Some of the submitted values are invalid." },
} satisfies Record<string, { vi: string; en: string }>

export const strings: Record<string, { vi: string; en: string }> = entries

type EntryKey = keyof typeof entries
/** `media.photosAdded_one` also makes `media.photosAdded` a usable key. */
type PluralBase<K> = K extends `${infer Base}_one` ? Base : never

export type StringKey = EntryKey | PluralBase<EntryKey>
